import pandas as pd
import io
from fastapi.responses import StreamingResponse # pyright: ignore[reportMissingImports]
from fastapi import UploadFile, File, HTTPException # pyright: ignore[reportMissingImports]

async def Ferrule(
        file: UploadFile = File(...)
        ):
    if not file.filename:
        raise HTTPException(status_code=400, detail="Debe proporcionar ambos archivos")
        
    try:
        tequila_details = await file.read()
        # Intentamos leer el archivo como DataFrame especificando la codificación
        df = pd.read_csv(io.BytesIO(tequila_details), encoding='utf-16', delimiter='\t')
        df2 = df.copy()
        df3 = df.copy()
        df4 = df.copy()
        df5 = df.copy()
        ctr = 1

        #Cambiar S-ACCR-ISTL-GRN-125-X-9, S-ACCR-ISTL-GRN-125-X-W por S-ACCR-ISTL-GRN-125-X-9W
        df['Inventory Identifier'] = df['Inventory Identifier'].str.strip()
        df.loc[df['Inventory Identifier'] == 'S-ACCR-ISTL-GRN-125-X-9', ['Inventory Identifier']] = ['S-ACCR-ISTL-GRN-125-X-9W']
        #df.loc[df['Inventory Identifier'] == 'S-ACCR-ISTL-GRN-125-X-W', ['Inventory Identifier']] = ['S-ACCR-ISTL-GRN-125-X-9W']
        
        #Cambios 115 a 100
        df.loc[df['Inventory Identifier'] == 'S-KBS-STPERLITE100-S-3', ['Inventory Identifier']] = ['S-KBS-STPERLITE115-S-3']
        df.loc[df['Inventory Identifier'] == 'S-KBS-STPERLITE100-S-4', ['Inventory Identifier']] = ['S-KBS-STPERLITE115-S-4']
        df.loc[df['Inventory Identifier'] == 'S-KBS-STPERLITE100-S-5', ['Inventory Identifier']] = ['S-KBS-STPERLITE115-S-5']
        df.loc[df['Inventory Identifier'] == 'S-KBS-STPERLITE100-S-6', ['Inventory Identifier']] = ['S-KBS-STPERLITE115-S-6']
        #df.loc[df['Inventory Identifier'] == 'S-KBS-STPERLITE100-S-7', ['Inventory Identifier']] = ['S-KBS-STPERLITE115-S-7']
        df.loc[df['Inventory Identifier'] == 'S-KBS-STPERLITE100-S-8', ['Inventory Identifier']] = ['S-KBS-STPERLITE115-S-8']

        #Convertir Kist de weighkit a piezas
        #df.loc[df['Inventory Identifier'] == 'A-WEIGHTKIT-DRIVER', ['Shipped Qty']] *= 8

        #Preparando data Iron
        df2['ID'] = df2['Finished Good Name'].str[:1]
        df2 = df2.loc[df2['ID'] == 'I']
        df2['Inventory Identifier'] = df2['Inventory Identifier'].str.strip()
        df2['Parte'] = ''
        df2['Descripcion'] = ''

        #Lista de Iron que utilizan Ferrule         
        df2.loc[df2['Inventory Identifier'] == 'S-ACCR-50I', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ACCR-60I', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ACCR-70I', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ACCR-80I', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-95R-CW-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-95R-CW-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-95R-CW-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-95R-CW-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-95R-CW-WDG', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-95S-CW-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105R-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-105S-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120S-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-120X-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-X100-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-X100-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-X100-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-X100-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-X100-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-X100-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER120-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPER130-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-CTPERLITE110-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-110-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-120-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-130-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-105-S-W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-TAPER-125-X-W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-R-PW', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-950GH-S-PW', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105R-W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-105S-PW', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120S-PW', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-2', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-9', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-NIP-MODPRO-120X-PW', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-6.5-40.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-36.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.0-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-36.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-37', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-37.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-38', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-38.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-39', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-39.5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-LZ-6.5-40', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-3', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-4', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-5', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-6', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-7', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-8', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-9W', ['Parte','Descripcion']] = ['T-IRON-FERRULE-.355','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-BLKRSV-110S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-BLKRSV-60A', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-BLKRSV-70R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-BLKRSV-95R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-AERO-BLKRSV-95S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ALDI-NVORG-HYB-85R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ALDI-NVSORG-55A-NXT', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-95-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-MID-115-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-MID-115-S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELEVATEMP-95-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-ELEVATEMP-95-S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-MAXGRPH-45-L-IRON', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-MAXGRPH-55-A-IRON', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-MAXGRPH-65-R-IRON', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-STAPER-LITE-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-70R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-80S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-LITE-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-KBS-TOUR-LITE-X', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-50-L', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-60-A', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-70-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-MMT-80-S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PROJX-CYPHER-40I-4.0', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PROJX-CYPHER-60I-5.5', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-CYPHER2.0-40I-4.0', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-CYPHER2.0-50I-5.0', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-PX-CYPHER2.0-60I-5.5', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-MID-115-X', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-USTM-HELBLK-5-F4', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-USTM-RECDART-55F1-L', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-USTM-RECDART-65F2-A', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-USTM-RECDART-75F3-R', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-USTM-RECDART-75F4-S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        df2.loc[df2['Inventory Identifier'] == 'S-DG-95-S', ['Parte','Descripcion']] = ['T-FERRULE-IRON-360','Build Materials']
        


        #Limpieza de data Iron
        shaftdf2 = df2.loc[df2['Descripcion'] == 'Build Materials']
        df2shaft = shaftdf2.reindex(columns=['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Parte','Descripcion','Shipped Qty','Shipped Clubs'])
        encabezados = ['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Inventory Identifier','Descr (INItemClass)','Shipped Qty','Shipped Clubs']
        df2shaft.columns = encabezados

        #Preparando data Wedge
        df3['ID'] = df3['Finished Good Name'].str[:1]
        df3 = df3.loc[df3['ID'] == 'W']
        df3['Inventory Identifier'] = df3['Inventory Identifier'].str.strip()
        df3['Parte'] = ''
        df3['Descripcion'] = ''

        #Lista de Wedge que utilizan ferrule
        df3.loc[df3['Inventory Identifier'] == 'S-ACCR-50I', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ACCR-60I', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ACCR-70I', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ACCR-80I', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-95R-CW-4', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-95R-CW-5', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-95R-CW-7', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-95R-CW-8', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-95R-CW-WDG', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-105R-37', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-105S-37', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-120S-37', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-120X-37', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-S400-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-X100-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-CTPER120-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-CTPER130-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-CTPERLITE110-9', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-STPERLITE115-S-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-110-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-120-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-130-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-MMT-TAPER-105-S-W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-MMT-TAPER-125-X-W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-NIP-950GH-R-PW', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-NIP-950GH-S-PW', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-NIP-MODPRO-105R-W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-NIP-MODPRO-105S-PW', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-NIP-MODPRO-120S-PW', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-NIP-MODPRO-120X-PW', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PX-6.5-37', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PX-LZ-6.0-36.5', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PX-LZ-6.5-36.5', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-PVD-110-R-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-PVD-120-S-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-PVD-130-X-9W', ['Parte','Descripcion']] = ['T-WEDGE-FERRULE-.355','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-BLKRSV-110S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-BLKRSV-60A', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-BLKRSV-70R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-BLKRSV-95R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-AERO-BLKRSV-95S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ALDI-NVORG-HYB-85R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ALDI-NVSORG-55A-NXT', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-115S-37', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-95-R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-MID-115-R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-MID-115-S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ELEVATEMP-95-R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-ELEVATEMP-95-S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-MAXGRPH-45-L-IRON', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-MAXGRPH-55-A-IRON', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-MAXGRPH-65-R-IRON', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-STAPER-LITE-R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-70R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-KBS-TOUR-80S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-MMT-50-L', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-MMT-60-A', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-MMT-70-R', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-MMT-80-S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PROJX-CYPHER-40I-4.0', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PROJX-CYPHER-60I-5.5', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PX-CYPHER2.0-40I-4.0', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PX-CYPHER2.0-50I-5.0', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-PX-CYPHER2.0-60I-5.5', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-MID-115-X', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']
        df3.loc[df3['Inventory Identifier'] == 'S-DG-95-S', ['Parte','Descripcion']] = ['T-FERRULE-WEDGE-360','Build Materials']

        #Lumpia de datos Wedge
        shaftdf3 = df3.loc[df3['Descripcion'] == 'Build Materials']
        df3shaft = shaftdf3.reindex(columns=['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Parte','Descripcion','Shipped Qty','Shipped Clubs'])
        encabezados3 = ['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Inventory Identifier','Descr (INItemClass)','Shipped Qty','Shipped Clubs']
        df3shaft.columns = encabezados3

        if ctr == 1: 

            #Limpieza de data A-SHAFT-ADAPTER-CTR
            df4['Inventory Identifier'] = df4['Inventory Identifier'].str.strip()
            df4['Parte'] = ''
            df4['Descripcion'] = ''

            #Lista de Shaft que llevan A-SHAFT-ADAPTER-CTR
            df4.loc[df4['Inventory Identifier'] == 'S-AERO-95R-CW-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-AERO-95R-CW-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-AERO-95R-CW-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-AERO-95R-CW-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-AERO-95R-CW-WDG', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-AERO-95S-CW-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105R-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-105S-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120S-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-120X-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-S400-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-DG-X100-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-S-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-ELVTETOUR-V2-X-W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER120-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-CTPER130-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-110-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-120-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-KBS-TOUR-130-9W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-105-S-W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-MMT-TAPER-125-X-W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-R-PW', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-950GH-S-PW', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105R-W', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-105S-PW', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120S-PW', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-2', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-3', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-4', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-6', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-7', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-8', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-9', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-NIP-MODPRO-120X-PW', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-6.5-40.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-36.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.0-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-36.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-37', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-37.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-38', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-38.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-39', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-39.5', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']
            df4.loc[df4['Inventory Identifier'] == 'S-PX-LZ-6.5-40', ['Parte','Descripcion']] = ['A-SHAFT-CTR-PC','Build Materials']

            #Limpieza de data A-SHAFT-CTR-PC
            shaftdf4 = df4.loc[df4['Descripcion'] == 'Build Materials']
            df4shaft = shaftdf4.reindex(columns=['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Parte','Descripcion','Shipped Qty','Shipped Clubs'])
            encabezados = ['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Inventory Identifier','Descr (INItemClass)','Shipped Qty','Shipped Clubs']
            df4shaft.columns = encabezados

            #Preparando Data T-PUTTER FERRULE 1
            df5['Inventory Identifier'] = df5['Inventory Identifier'].str.strip()
            df5['Parte'] = ''
            df5['Descripcion'] = ''

            #Lista de T-PUTTER FERRULE 1
            df5.loc[df5['Inventory Identifier'] == 'PL3-ARMLOCK-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PL3-DOUBLEBEND-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PL3-H-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PR3-ARMLOCK-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PR3-DOUBLEBEND-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PR3-H-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PU3-CENTER-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']

            #Limpieza de data T-PUTTER FERRULE 1
            shaftdf5 = df5.loc[df5['Descripcion'] == 'Build Materials']
            df5shaft = shaftdf5.reindex(columns=['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Parte','Descripcion','Shipped Qty','Shipped Clubs'])
            encabezados = ['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Inventory Identifier','Descr (INItemClass)','Shipped Qty','Shipped Clubs']
            df5shaft.columns = encabezados

            #Unificacion y creacion del nuevo archivo
            df6 = pd.concat([df, df2shaft, df3shaft, df4shaft,df5shaft])
            df6 = df6.sort_values(by=['ShipmentNbr','Line ID'])

            output = io.BytesIO()
            df6.to_csv(output, encoding='utf-16', sep='\t', index=False)
            output.seek(0)
            return StreamingResponse(
                output,
                media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                headers={
                    'Content-Disposition': 'attachment; filename="Bank_Deposit_Upload_Adyen.xlsx"'
                }
            )
        
        else:
            #Preparando Data T-PUTTER FERRULE 1
            df5['Inventory Identifier'] = df5['Inventory Identifier'].str.strip()
            df5['Parte'] = ''
            df5['Descripcion'] = ''

            #Lista de T-PUTTER FERRULE 1
            df5.loc[df5['Inventory Identifier'] == 'PL3-ARMLOCK-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PL3-DOUBLEBEND-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PL3-H-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PR3-ARMLOCK-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PR3-DOUBLEBEND-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PR3-H-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']
            df5.loc[df5['Inventory Identifier'] == 'PU3-CENTER-HOS-BLK', ['Parte','Descripcion']] = ['T-PUTTER FERRULE 1','Build Materials']

            #Limpieza de data T-PUTTER FERRULE 1
            shaftdf5 = df5.loc[df5['Descripcion'] == 'Build Materials']
            df5shaft = shaftdf5.reindex(columns=['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Parte','Descripcion','Shipped Qty','Shipped Clubs'])
            encabezados = ['ShipmentStatus','ShipmentNbr','Line ID','Finished Good Name','Inventory Identifier','Descr (INItemClass)','Shipped Qty','Shipped Clubs']
            df5shaft.columns = encabezados

            #Unificacion y creacion del nuevo archivo
            df6 = pd.concat([df, df2shaft, df3shaft, df5shaft])
            df6 = df6.sort_values(by=['ShipmentNbr','Line ID'])

            output = io.BytesIO()
            df6.to_csv(output, encoding='utf-16', sep='\t', index=False)
            output.seek(0)
            return StreamingResponse(
                output,
                media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                headers={
                    'Content-Disposition': 'attachment; filename="Bank_Deposit_Upload_Adyen.xlsx"'
                }
            )
    
    except UnicodeDecodeError:
        raise HTTPException(status_code=400, detail="Error de codificación. Intente guardar los archivos como UTF-8 BOM")
    except pd.errors.ParserError:
        raise HTTPException(status_code=400, detail="Error al analizar el CSV. Verifique el delimitador (usar coma o punto y coma)")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error inesperado: {str(e)}")