import re
import pandas as pd
import io
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from fastapi.responses import StreamingResponse # pyright: ignore[reportMissingImports]
from fastapi import UploadFile, File, HTTPException # pyright: ignore[reportMissingImports]
import numpy as np
from typing import List
from io import BytesIO
async def ValidationReceipt(
        file: UploadFile = File(...)
        ):
    # Verificación básica de archivos
    if not file.filename:
        raise HTTPException(status_code=400, detail= "Archivo no seleccionado")
    try:
        recibofile = await file.read()
        dfrecibo = pd.read_excel(io.BytesIO(recibofile), sheet_name='Transfers', header=1)    
        dfrecibo_details = pd.read_excel(io.BytesIO(recibofile), sheet_name='Transfers', header=1)

        pattern = r'^(B-|GB|G4|H-|PB|A-J|A-1|A-A|A-D|A-I|A-N|A-Q|A-U|A-Z)'

        mask = dfrecibo['Inventory ID'].astype(str).str.match(pattern)

        dfrecibo.loc[mask, 'Inventory ID'] = (
            dfrecibo.loc[mask, 'Inventory ID'].astype(str) + '-MS'
        )

        mask2 = dfrecibo['Inventory ID.1'].astype(str).str.match(pattern)

        dfrecibo.loc[mask2, 'Inventory ID.1'] = (
            dfrecibo.loc[mask2, 'Inventory ID.1'].astype(str) + '-MS'
        )

        mask_details = dfrecibo_details['Inventory ID'].astype(str).str.match(pattern)

        dfrecibo_details.loc[mask_details, 'Inventory ID'] = (
            dfrecibo_details.loc[mask_details, 'Inventory ID'].astype(str) + '-MS'
        )

        mask2_details = dfrecibo_details['Inventory ID.1'].astype(str).str.match(pattern)

        dfrecibo_details.loc[mask2_details, 'Inventory ID.1'] = (
            dfrecibo_details.loc[mask2_details, 'Inventory ID.1'].astype(str) + '-MS'
        )

        # Función para procesar cada grupo de columnas
        def procesar_grupo(dfrecibo, id_col, desc_col, qty_col):
            """
            Agrupa por Inventory ID y suma las cantidades
            """
            # Seleccionar solo las columnas relevantes
            grupo = dfrecibo[[id_col, qty_col]].copy()
            # Renombrar columnas para facilitar el trabajo
            grupo.columns = ['Inventory_ID', 'Quantity']
            # Eliminar filas con ID nulo o vacío
            grupo = grupo[grupo['Inventory_ID'].notna()]
            # Agrupar y sumar
            grupo_agrupado = grupo.groupby('Inventory_ID')['Quantity'].sum().reset_index()
            return grupo_agrupado
        nps = [
            "139380",
            "156148",
            "1516001",
            "2290-0002",
            "2290-0003",
            "2290-0137",
            "9023-2425",
            "95181324-BA",
            "A-TORQUETOOL",
            "A-TORQUETOOL-GEN4IR",
            "B-1484781",
            "B-14CLUBSHIPPER",
            "B-1517171",
            "B-1517173",
            "B-1517175",
            "B-1517180",
            "B-632517",
            "B-COMPACT-IRON",
            "B-COMPACT-PUTTER",
            "B-COMPACT-WEDGE",
            "B-COMPACT-WOODS",
            "B-IRONFOAM",
            "B-PG-082-WHT-MS",
            "B-PG-172-DW-MS",
            "B-UGB10-EP-MS",
            "B-UGB7-EP",
            "B-UGB7-EP-MS",
            "B-UGB8-EP",
            "B-UGB8-EP-MS",
            "B-UGB9-EP",
            "B-UGB9-EP-MS",
            "B-WOODFOAM",
            "CTPER120",
            "DL-PXG10-12",
            "DL-PXG12-9",
            "DL-PXG18-10.5",
            "DL-PXG18-7.5",
            "DL-PXG18-9",
            "DL-PXG19-10.5",
            "DL-PXG19-9",
            "DL-PXG20-10.5",
            "DL-PXG20-7.5",
            "DL-PXG20-9",
            "DL-PXG21-10.5",
            "DL-PXG21-12",
            "DL-PXG21-9",
            "DL-PXG23-10.5",
            "DL-PXG23-12",
            "DL-PXG23-9",
            "DL-PXG24-9",
            "DR-PXG10-10.5",
            "DR-PXG12-10.5",
            "DR-PXG12-12",
            "DR-PXG12-7.5",
            "DR-PXG12-9",
            "DR-PXG13-10.5",
            "DR-PXG13-7.5",
            "DR-PXG14-10.5",
            "DR-PXG14-12",
            "DR-PXG15-10.5",
            "DR-PXG15-12",
            "DR-PXG15-9",
            "DR-PXG16-16",
            "DR-PXG17-10.5",
            "DR-PXG17-12",
            "DR-PXG17-9",
            "DR-PXG18-10.5",
            "DR-PXG18-7.5",
            "DR-PXG18-9",
            "DR-PXG19-10.5",
            "DR-PXG19-12",
            "DR-PXG19-9",
            "DR-PXG20-10.5",
            "DR-PXG20-7.5",
            "DR-PXG20-9",
            "DR-PXG21-10.5",
            "DR-PXG21-12",
            "DR-PXG21-9",
            "DR-PXG23-10.5",
            "DR-PXG23-12",
            "DR-PXG23-8",
            "DR-PXG23-9",
            "DR-PXG24-10.5",
            "DR-PXG24-8",
            "DR-PXG24-9",
            "DR-PXG9-9",
            "DYELTS",
            "DYMPH95R",
            "DYMPH95S",
            "DYMPH-95S",
            "FL-PXG12-4",
            "FL-PXG13-2",
            "FL-PXG13-3",
            "FL-PXG13-5",
            "FL-PXG13-7",
            "FL-PXG14-3",
            "FL-PXG14-4",
            "FL-PXG14-5",
            "FL-PXG14-7",
            "FL-PXG15-3",
            "FL-PXG15-4",
            "FL-PXG15-5",
            "FL-PXG15-7",
            "FL-PXG15-9",
            "FR-PXG10-3",
            "FR-PXG10-5",
            "FR-PXG10-7",
            "FR-PXG11-2",
            "FR-PXG11-3",
            "FR-PXG11-7",
            "FR-PXG12-3",
            "FR-PXG12-5",
            "FR-PXG13-2",
            "FR-PXG13-3",
            "FR-PXG13-5",
            "FR-PXG13-7",
            "FR-PXG14-3",
            "FR-PXG14-4",
            "FR-PXG14-5",
            "FR-PXG14-7",
            "FR-PXG15-3",
            "FR-PXG15-4",
            "FR-PXG15-5",
            "FR-PXG15-7",
            "FR-PXG15-9",
            "FR-PXG5-7",
            "FR-PXG6-3",
            "FR-PXG6-5",
            "FR-PXG7-2S",
            "FR-PXG7-3S",
            "FR-PXG7-5",
            "FR-PXG7-7",
            "FR-PXG8-18",
            "FR-PXG9-3",
            "FR-PXG9-5",
            "FR-PXG9-7",
            "GB-DOZ-XTREME-MS",
            "GB-DOZ-XTREME-NAVY",
            "G-GP-CP2MID-PRO",
            "G-GP-CP2MID-W",
            "G-GP-CP2PRO-STD",
            "G-GP-CP2WRAP-STD",
            "G-GP-MC-MID-WHT",
            "G-GP-MCPLUS4A-STD-GRY",
            "G-GP-MCPLUS4-MID-GRY",
            "G-GP-MCPLUS4-STD-GRY",
            "G-GP-MC-STD-WHITE",
            "G-GP-TOURV-58-RIB",
            "G-GP-TOURV-58-UND",
            "G-GP-TOURV-60-STD",
            "G-GP-TOURV-CORD",
            "G-GP-TOURV-MID",
            "G-GP-TOURW-58R-BLK",
            "G-GP-TOURW-58R-WHITE",
            "G-GP-TOURW-60R-MBLK",
            "G-GP-TOURW-60R-MWHT",
            "G-GP-TOURZ-MID-CORD",
            "G-GP-TOURZ-STD-CORD",
            "G-GP-TV360-BLK-MID",
            "G-GP-TV360-BLK-OVR",
            "G-GP-TV360-BLK-STD",
            "G-GP-TV360-BLK-UND",
            "G-LAMK-PXG-PISTOL",
            "G-LAMK-PXG-SKINNY",
            "G-LAMK-Z5-MID-BLK",
            "G-LAMK-Z5-OVR-BLK",
            "G-LAMK-Z5-STD-BLK",
            "G-LAMK-Z5-STD-DEMO",
            "G-LAMK-Z5-UND-BLK",
            "G-PXG-PG-PST-I-BLK",
            "G-PXG-PG-PST-II-BLK",
            "G-PXG-PG-PST-III-BLK",
            "G-PXG-PG-STR-I-BLK",
            "G-PXG-PG-STR-II-BLK",
            "G-PXG-PG-STR-III-BLK",
            "G-PXG-PG-STR-XL-BLK",
            "G-SS-17PXG-FLATSO2.0",
            "G-SS-17PXG-FLATSO3.0",
            "G-SS-2017PXG-FLATSO",
            "G-SS-2017PXG-MS2.0",
            "G-SS-2017PXG-MS2.0XL",
            "G-SS-2017PXG-MS3.0",
            "G-SS-2017PXG-MS5.0",
            "G-SS-2017PXG-PISTOL",
            "G-SS-PXG-1.3-17",
            "G-WINN-DRI-MID-GR",
            "G-WINN-DRI-OVR-GR",
            "G-WINN-DRI-STD-GR",
            "G-WINN-DRI-UNDR-GR",
            "G-WINN-DRIWRP-MID-GR",
            "G-WINN-DRIWRP-OVR-GR",
            "G-WINN-DRIWRP-STD-GR",
            "H-22PXG000002-BLK-MS",
            "H-22PXG000002-WHT",
            "H-22PXG000002-WHT-MS",
            "H-22PXG000007-BLK-MS",
            "H-22PXG000009-BLK",
            "H-22PXG000009-BLK-MS",
            "H-22PXG000009-WHT-MS",
            "H-22PXG000030-BLK-GRY",
            "H-22PXG000030-BLK-WHT",
            "H-22PXG000033-WHT-BLK",
            "H-60238390-SM",
            "H-60245259",
            "H-60286693",
            "H-60296173",
            "H-60362870",
            "HC-1304-RLMALSB",
            "HC2-2020-BLADE-BLK",
            "HC2-2020-DRIVER-BLK",
            "HC2-2020-DRKBLADE-BLK",
            "HC2-2020-DRKHLFMAL-BLK",
            "HC2-2020-DRKMALLET-BLK",
            "HC2-2020-DRKMALLET-C-BLK",
            "HC2-2020-DRKWDBLADE-BLK",
            "HC2-2020-FAIRWAY-BLK",
            "HC2-2020-HYBRID-BLK",
            "HC2-2020-MALLET-BLK",
            "HC2-2020-PATCH-FW2",
            "HC2-2020-PATCH-FW3",
            "HC2-2020-PATCH-FW4",
            "HC2-2020-PATCH-FW5",
            "HC2-2020-PATCH-FW7",
            "HC2-2020-PATCH-HYB17",
            "HC2-2020-PATCH-HYB19",
            "HC2-2020-PATCH-HYB22",
            "HC2-2020-PATCH-HYB25",
            "HC2-2020-PATCH-HYB28",
            "HC2-2020-PATCH-HYB31",
            "HC2-2020-WIDEBLADE-BLK",
            "HC2-GEN2-MALLET-BLK",
            "HC2-GEN4-DRIVER-GRY",
            "HC2-GEN4-FAIRWAY-GRY",
            "HC2-GEN4-HYBRID-GRY",
            "HC2-GEN4-PATCH-FW2",
            "HC2-GEN4-PATCH-FW3",
            "HC2-GEN4-PATCH-FW5",
            "HC2-GEN4-PATCH-FW7",
            "HC2-GEN4-PATCH-HYB17",
            "HC2-GEN4-PATCH-HYB19",
            "HC2-GEN4-PATCH-HYB22",
            "HC2-GEN4-PATCH-HYB25",
            "HC2-GEN4-PATCH-HYB28",
            "HC2-GEN5-DRIVER-BLK",
            "HC2-GEN5-FAIRWAY-BLK",
            "HC2-GEN5-HYBRID-BLK",
            "HC2-GEN5-PATCH-17",
            "HC2-GEN5-PATCH-19",
            "HC2-GEN5-PATCH-2",
            "HC2-GEN5-PATCH-22",
            "HC2-GEN5-PATCH-25",
            "HC2-GEN5-PATCH-28",
            "HC2-GEN5-PATCH-3",
            "HC2-GEN5-PATCH-31",
            "HC2-GEN5-PATCH-4",
            "HC2-GEN5-PATCH-5",
            "HC2-GEN5-PATCH-7",
            "HC-GEN6-DRIVER-BLK",
            "HC-GEN6-FAIRWAY-BLK",
            "HC-GEN6-HYBRID-BLK",
            "HC-GEN6-PATCH-17",
            "HC-GEN6-PATCH-19",
            "HC-GEN6-PATCH-2",
            "HC-GEN6-PATCH-22",
            "HC-GEN6-PATCH-25",
            "HC-GEN6-PATCH-28",
            "HC-GEN6-PATCH-3",
            "HC-GEN6-PATCH-31",
            "HC-GEN6-PATCH-4",
            "HC-GEN6-PATCH-5",
            "HC-GEN6-PATCH-7",
            "HC-GEN6-PATCH-9",
            "HC-ICU65199PXG-APC",
            "HC-ICU65199PXG-BLD",
            "HC-ICU65199PXG-CM",
            "HC-ICU65199PXG-HLF",
            "HC-ICU65199PXG-MAL",
            "HC-ICU66579GEN7-DR",
            "HC-ICU66579GEN7-FW",
            "HC-ICU66579GEN7-HY",
            "HL-PXG11-22",
            "HL-PXG11-25",
            "HL-PXG12-22",
            "HL-PXG12-25",
            "HL-PXG13-17",
            "HL-PXG13-19",
            "HL-PXG13-22",
            "HL-PXG13-25",
            "HL-PXG14-19",
            "HL-PXG14-22",
            "HL-PXG14-25",
            "HL-PXG14-28",
            "HL-PXG14-31",
            "HL-PXG15-17",
            "HL-PXG15-19",
            "HL-PXG15-22",
            "HL-PXG15-25",
            "HL-PXG15-28",
            "HL-PXG15-31",
            "HR-PXG10-19",
            "HR-PXG10-22",
            "HR-PXG10-25",
            "HR-PXG10-28",
            "HR-PXG11-17",
            "HR-PXG11-22",
            "HR-PXG11-25",
            "HR-PXG12-19",
            "HR-PXG12-22",
            "HR-PXG12-25",
            "HR-PXG12-28",
            "HR-PXG13-17",
            "HR-PXG13-19",
            "HR-PXG13-22",
            "HR-PXG13-25",
            "HR-PXG14-19",
            "HR-PXG14-22",
            "HR-PXG14-25",
            "HR-PXG14-28",
            "HR-PXG14-31",
            "HR-PXG15-17",
            "HR-PXG15-19",
            "HR-PXG15-22",
            "HR-PXG15-25",
            "HR-PXG15-28",
            "HR-PXG15-31",
            "HR-PXG5-17",
            "HR-PXG5-19",
            "HR-PXG5-22",
            "HR-PXG5-25",
            "HR-PXG5-28",
            "HR-PXG6-22",
            "HR-PXG6-25",
            "HR-PXG7-19",
            "HR-PXG7-22",
            "HR-PXG7-25",
            "HR-PXG7-28",
            "HR-PXG8-25",
            "HR-PXG9-19",
            "HR-PXG9-22",
            "HR-PXG9-25",
            "HR-PXG9-28",
            "H-UHW32-EP-B",
            "IL-PXG28-5",
            "IL-PXG29-4",
            "IL-PXG29-4-BLK",
            "IL-PXG29-5",
            "IL-PXG29-5-BLK",
            "IL-PXG29-6",
            "IL-PXG29-6-BLK",
            "IL-PXG29-7",
            "IL-PXG29-7-BLK",
            "IL-PXG29-8",
            "IL-PXG29-8-BLK",
            "IL-PXG29-9",
            "IL-PXG29-9-BLK",
            "IL-PXG29-GW",
            "IL-PXG29-GW-BLK",
            "IL-PXG29-PW",
            "IL-PXG29-PW-BLK",
            "IL-PXG30-4",
            "IL-PXG30-4-BLK",
            "IL-PXG30-5",
            "IL-PXG30-5-BLK",
            "IL-PXG30-6",
            "IL-PXG30-6-BLK",
            "IL-PXG30-7",
            "IL-PXG30-7-BLK",
            "IL-PXG30-8",
            "IL-PXG30-8-BLK",
            "IL-PXG30-9",
            "IL-PXG30-9-BLK",
            "IL-PXG30-GW",
            "IL-PXG30-GW-BLK",
            "IL-PXG30-PW",
            "IL-PXG30-PW-BLK",
            "IL-PXG31-X-BLK",
            "IL-PXG33-3",
            "IL-PXG33-3-BLK",
            "IL-PXG33-4",
            "IL-PXG33-4-BLK",
            "IL-PXG33-5",
            "IL-PXG33-5-BLK",
            "IL-PXG33-6",
            "IL-PXG33-6-BLK",
            "IL-PXG33-7",
            "IL-PXG33-7-BLK",
            "IL-PXG33-8",
            "IL-PXG33-8-BLK",
            "IL-PXG33-9",
            "IL-PXG33-9-BLK",
            "IL-PXG33-GW",
            "IL-PXG33-GW-BLK",
            "IL-PXG33-PW",
            "IL-PXG33-PW-BLK",
            "IL-PXG34-3",
            "IL-PXG34-4",
            "IL-PXG34-5",
            "IL-PXG34-6",
            "IL-PXG34-7",
            "IL-PXG34-8",
            "IL-PXG34-9",
            "IL-PXG34-GW",
            "IL-PXG34-PW",
            "IL-PXG36-4",
            "IL-PXG36-4-BB",
            "IL-PXG36-4-BLK",
            "IL-PXG36-4-CC",
            "IL-PXG36-5",
            "IL-PXG36-5-BB",
            "IL-PXG36-5-BLK",
            "IL-PXG36-5-CC",
            "IL-PXG36-6",
            "IL-PXG36-6-BB",
            "IL-PXG36-6-BLK",
            "IL-PXG36-6-CC",
            "IL-PXG36-7",
            "IL-PXG36-7-BB",
            "IL-PXG36-7-BLK",
            "IL-PXG36-7-CC",
            "IL-PXG36-8",
            "IL-PXG36-8-BB",
            "IL-PXG36-8-BLK",
            "IL-PXG36-8-CC",
            "IL-PXG36-9",
            "IL-PXG36-9-BB",
            "IL-PXG36-9-BLK",
            "IL-PXG36-9-CC",
            "IL-PXG36-GW",
            "IL-PXG36-GW-BB",
            "IL-PXG36-GW-BLK",
            "IL-PXG36-GW-CC",
            "IL-PXG36-LW",
            "IL-PXG36-LW-BB",
            "IL-PXG36-LW-BLK",
            "IL-PXG36-LW-CC",
            "IL-PXG36-PW",
            "IL-PXG36-PW-BB",
            "IL-PXG36-PW-BLK",
            "IL-PXG36-PW-CC",
            "IL-PXG36-SW",
            "IL-PXG36-SW-BB",
            "IL-PXG36-SW-BLK",
            "IL-PXG36-SW-CC",
            "IL-PXG37-4",
            "IL-PXG37-4-BB",
            "IL-PXG37-4-BLK",
            "IL-PXG37-4-CC",
            "IL-PXG37-5",
            "IL-PXG37-5-BB",
            "IL-PXG37-5-BLK",
            "IL-PXG37-5-CC",
            "IL-PXG37-6",
            "IL-PXG37-6-BB",
            "IL-PXG37-6-BLK",
            "IL-PXG37-6-CC",
            "IL-PXG37-7",
            "IL-PXG37-7-BB",
            "IL-PXG37-7-BLK",
            "IL-PXG37-7-CC",
            "IL-PXG37-8",
            "IL-PXG37-8-BB",
            "IL-PXG37-8-BLK",
            "IL-PXG37-8-CC",
            "IL-PXG37-9",
            "IL-PXG37-9-BB",
            "IL-PXG37-9-BLK",
            "IL-PXG37-9-CC",
            "IL-PXG37-GW",
            "IL-PXG37-GW-BB",
            "IL-PXG37-GW-BLK",
            "IL-PXG37-GW-CC",
            "IL-PXG37-PW",
            "IL-PXG37-PW-BB",
            "IL-PXG37-PW-BLK",
            "IL-PXG37-PW-CC",
            "IL-PXG38-X",
            "IL-PXG39-4",
            "IL-PXG39-4-BLK",
            "IL-PXG39-5",
            "IL-PXG39-5-BLK",
            "IL-PXG39-6",
            "IL-PXG39-6-BLK",
            "IL-PXG39-7",
            "IL-PXG39-7-BLK",
            "IL-PXG39-8",
            "IL-PXG39-8-BLK",
            "IL-PXG39-9",
            "IL-PXG39-9-BLK",
            "IL-PXG39-GW",
            "IL-PXG39-GW-BLK",
            "IL-PXG39-PW",
            "IL-PXG39-PW-BLK",
            "IL-PXG40-4",
            "IL-PXG40-4-BLK",
            "IL-PXG40-5",
            "IL-PXG40-5-BLK",
            "IL-PXG40-6",
            "IL-PXG40-6-BLK",
            "IL-PXG40-7",
            "IL-PXG40-7-BLK",
            "IL-PXG40-8",
            "IL-PXG40-8-BLK",
            "IL-PXG40-9",
            "IL-PXG40-9-BLK",
            "IL-PXG40-GW",
            "IL-PXG40-GW-BLK",
            "IL-PXG40-LW",
            "IL-PXG40-LW-BLK",
            "IL-PXG40-PW",
            "IL-PXG40-PW-BLK",
            "IL-PXG40-SW",
            "IL-PXG40-SW-BLK",
            "IR-PXG15-4",
            "IR-PXG15-5",
            "IR-PXG15-6",
            "IR-PXG15-7",
            "IR-PXG15-8",
            "IR-PXG15-9",
            "IR-PXG15-GW",
            "IR-PXG15-PW",
            "IR-PXG16-3",
            "IR-PXG16-5",
            "IR-PXG16-6",
            "IR-PXG16-7",
            "IR-PXG16-8",
            "IR-PXG16-9",
            "IR-PXG16-PW",
            "IR-PXG18-5",
            "IR-PXG18-6",
            "IR-PXG18-7",
            "IR-PXG18-8",
            "IR-PXG18-9",
            "IR-PXG18-GW",
            "IR-PXG18-PW",
            "IR-PXG18-SW",
            "IR-PXG19-4",
            "IR-PXG21-3",
            "IR-PXG21-3-BLK",
            "IR-PXG21-4",
            "IR-PXG21-4-BLK",
            "IR-PXG21-5",
            "IR-PXG21-5-BLK",
            "IR-PXG21-6",
            "IR-PXG21-6-BLK",
            "IR-PXG21-7",
            "IR-PXG21-7-BLK",
            "IR-PXG21-8",
            "IR-PXG21-8-BLK",
            "IR-PXG21-9",
            "IR-PXG21-9-BLK",
            "IR-PXG21-GW",
            "IR-PXG21-GW-BLK",
            "IR-PXG21-PW",
            "IR-PXG21-PW-BLK",
            "IR-PXG22-3",
            "IR-PXG22-3-BLK",
            "IR-PXG22-4",
            "IR-PXG22-4-BLK",
            "IR-PXG22-5",
            "IR-PXG22-5-BLK",
            "IR-PXG22-6",
            "IR-PXG22-6-BLK",
            "IR-PXG22-7",
            "IR-PXG22-7-BLK",
            "IR-PXG22-8",
            "IR-PXG22-8-BLK",
            "IR-PXG22-9",
            "IR-PXG22-9-BLK",
            "IR-PXG22-GW",
            "IR-PXG22-GW-BLK",
            "IR-PXG22-PW",
            "IR-PXG22-PW-BLK",
            "IR-PXG23-4",
            "IR-PXG23-4-BLK",
            "IR-PXG23-5",
            "IR-PXG23-5-BLK",
            "IR-PXG23-6",
            "IR-PXG23-6-BLK",
            "IR-PXG23-7",
            "IR-PXG23-7-BLK",
            "IR-PXG23-8",
            "IR-PXG23-8-BLK",
            "IR-PXG23-9",
            "IR-PXG23-9-BLK",
            "IR-PXG23-PW",
            "IR-PXG23-PW-BLK",
            "IR-PXG24-3-BLK",
            "IR-PXG24-4-BLK",
            "IR-PXG24-5-BLK",
            "IR-PXG24-6-BLK",
            "IR-PXG24-7-BLK",
            "IR-PXG24-8-BLK",
            "IR-PXG24-9-BLK",
            "IR-PXG24-GW-BLK",
            "IR-PXG24-PW-BLK",
            "IR-PXG26-X",
            "IR-PXG27-6",
            "IR-PXG27-7",   
            "IR-PXG27-8",
            "IR-PXG27-9",
            "IR-PXG27-S",
            "IR-PXG27-W",
            "IR-PXG28-4",
            "IR-PXG28-4-BLK",
            "IR-PXG28-5",
            "IR-PXG28-5-BLK",
            "IR-PXG28-6",
            "IR-PXG28-6-BLK",
            "IR-PXG28-7",
            "IR-PXG28-7-BLK",
            "IR-PXG28-8",
            "IR-PXG28-8-BLK",
            "IR-PXG28-9",
            "IR-PXG28-9-BLK",
            "IR-PXG28-GW",
            "IR-PXG28-GW-BLK",
            "IR-PXG28-PW",
            "IR-PXG28-PW-BLK",
            "IR-PXG29-4",
            "IR-PXG29-4-BLK",
            "IR-PXG29-5",
            "IR-PXG29-5-BLK",
            "IR-PXG29-6",
            "IR-PXG29-6-BLK",
            "IR-PXG29-7",
            "IR-PXG29-7-BLK",
            "IR-PXG29-8",
            "IR-PXG29-8-BLK",
            "IR-PXG29-9",
            "IR-PXG29-9-BLK",
            "IR-PXG29-GW",
            "IR-PXG29-GW-BLK",
            "IR-PXG29-PW",
            "IR-PXG29-PW-BLK",
            "IR-PXG30-4-BLK",
            "IR-PXG30-5",
            "IR-PXG30-5-BLK",
            "IR-PXG30-6",
            "IR-PXG30-6-BLK",
            "IR-PXG30-7",
            "IR-PXG30-7-BLK",
            "IR-PXG30-8",
            "IR-PXG30-8-BLK",
            "IR-PXG30-9",
            "IR-PXG30-9-BLK",
            "IR-PXG30-GW",
            "IR-PXG30-GW-BLK",
            "IR-PXG30-PW",
            "IR-PXG30-PW-BLK",
            "IR-PXG31-X",
            "IR-PXG31-X-BLK",
            "IR-PXG32-4",
            "IR-PXG32-4-BLK",
            "IR-PXG32-5",
            "IR-PXG32-5-BLK",
            "IR-PXG32-6",
            "IR-PXG32-6-BLK",
            "IR-PXG32-7",
            "IR-PXG32-7-BLK",
            "IR-PXG32-8",
            "IR-PXG32-8-BLK",
            "IR-PXG32-9",
            "IR-PXG32-9-BLK",
            "IR-PXG32-GW",
            "IR-PXG32-GW-BLK",
            "IR-PXG32-LW",
            "IR-PXG32-LW-BLK",
            "IR-PXG32-PW",
            "IR-PXG32-PW-BLK",
            "IR-PXG32-SW",
            "IR-PXG32-SW-BLK",
            "IR-PXG33-3",
            "IR-PXG33-3-BLK",
            "IR-PXG33-4",
            "IR-PXG33-4-BLK",
            "IR-PXG33-5",
            "IR-PXG33-5-BLK",
            "IR-PXG33-6",
            "IR-PXG33-6-BLK",
            "IR-PXG33-7",
            "IR-PXG33-7-BLK",
            "IR-PXG33-8",
            "IR-PXG33-8-BLK",
            "IR-PXG33-9",
            "IR-PXG33-9-BLK",
            "IR-PXG33-GW",
            "IR-PXG33-GW-BLK",
            "IR-PXG33-PW",
            "IR-PXG33-PW-BLK",
            "IR-PXG34-3",
            "IR-PXG34-3-BLK",
            "IR-PXG34-4",
            "IR-PXG34-4-BLK",
            "IR-PXG34-5",
            "IR-PXG34-5-BLK",
            "IR-PXG34-6",
            "IR-PXG34-6-BLK",
            "IR-PXG34-7",
            "IR-PXG34-7-BLK",
            "IR-PXG34-8",
            "IR-PXG34-8-BLK",
            "IR-PXG34-9",
            "IR-PXG34-9-BLK",
            "IR-PXG34-GW",
            "IR-PXG34-GW-BLK",
            "IR-PXG34-PW",
            "IR-PXG34-PW-BLK",
            "IR-PXG35-3",
            "IR-PXG35-3-BLK",
            "IR-PXG35-4",
            "IR-PXG35-4-BLK",
            "IR-PXG35-5",
            "IR-PXG35-5-BLK",
            "IR-PXG35-6",
            "IR-PXG35-6-BLK",
            "IR-PXG35-7",
            "IR-PXG35-7-BLK",
            "IR-PXG35-8",
            "IR-PXG35-8-BLK",
            "IR-PXG35-9",
            "IR-PXG35-9-BLK",
            "IR-PXG35-GW",
            "IR-PXG35-GW-BLK",
            "IR-PXG35-PW",
            "IR-PXG35-PW-BLK",
            "IR-PXG36-4",
            "IR-PXG36-4-BB",
            "IR-PXG36-4-BLK",
            "IR-PXG36-4-CC",
            "IR-PXG36-5",
            "IR-PXG36-5-BB",
            "IR-PXG36-5-BLK",
            "IR-PXG36-5-CC",
            "IR-PXG36-6",
            "IR-PXG36-6-BB",
            "IR-PXG36-6-BLK",
            "IR-PXG36-6-CC",
            "IR-PXG36-7",
            "IR-PXG36-7-BB",
            "IR-PXG36-7-BLK",
            "IR-PXG36-7-CC",
            "IR-PXG36-8",
            "IR-PXG36-8-BB",
            "IR-PXG36-8-BLK",
            "IR-PXG36-8-CC",
            "IR-PXG36-9",
            "IR-PXG36-9-BB",
            "IR-PXG36-9-BLK",
            "IR-PXG36-9-CC",
            "IR-PXG36-GW",
            "IR-PXG36-GW-BB",
            "IR-PXG36-GW-BLK",
            "IR-PXG36-GW-CC",
            "IR-PXG36-LW",
            "IR-PXG36-LW-BB",
            "IR-PXG36-LW-BLK",
            "IR-PXG36-LW-CC",
            "IR-PXG36-PW",
            "IR-PXG36-PW-BB",
            "IR-PXG36-PW-BLK",
            "IR-PXG36-PW-CC",
            "IR-PXG36-SW-BB",
            "IR-PXG36-SW-CC",
            "IR-PXG37-4",
            "IR-PXG37-4-BB",
            "IR-PXG37-4-BLK",
            "IR-PXG37-4-CC",
            "IR-PXG37-5",
            "IR-PXG37-5-BB",
            "IR-PXG37-5-BLK",
            "IR-PXG37-5-CC",
            "IR-PXG37-6",
            "IR-PXG37-6-BB",
            "IR-PXG37-6-BLK",
            "IR-PXG37-6-CC",
            "IR-PXG37-7",
            "IR-PXG37-7-BB",
            "IR-PXG37-7-BLK",
            "IR-PXG37-7-CC",
            "IR-PXG37-8",
            "IR-PXG37-8-BB",
            "IR-PXG37-8-BLK",
            "IR-PXG37-8-CC",
            "IR-PXG37-9",
            "IR-PXG37-9-BB",
            "IR-PXG37-9-BLK",
            "IR-PXG37-9-CC",
            "IR-PXG37-GW",
            "IR-PXG37-GW-BB",
            "IR-PXG37-GW-BLK",
            "IR-PXG37-GW-CC",
            "IR-PXG37-PW",
            "IR-PXG37-PW-BB",
            "IR-PXG37-PW-BLK",
            "IR-PXG37-PW-CC",
            "IR-PXG38-X",
            "IR-PXG39-4",
            "IR-PXG39-4-BLK",
            "IR-PXG39-5",
            "IR-PXG39-5-BLK",
            "IR-PXG39-6",
            "IR-PXG39-6-BLK",
            "IR-PXG39-7",
            "IR-PXG39-7-BLK",
            "IR-PXG39-8",
            "IR-PXG39-8-BLK",
            "IR-PXG39-9",
            "IR-PXG39-9-BLK",
            "IR-PXG39-GW",
            "IR-PXG39-GW-BLK",
            "IR-PXG39-PW",
            "IR-PXG39-PW-BLK",
            "IR-PXG40-4",
            "IR-PXG40-4-BLK",
            "IR-PXG40-5",
            "IR-PXG40-5-BLK",
            "IR-PXG40-6",
            "IR-PXG40-6-BLK",
            "IR-PXG40-7",
            "IR-PXG40-7-BLK",
            "IR-PXG40-8",
            "IR-PXG40-8-BLK",
            "IR-PXG40-9",
            "IR-PXG40-9-BLK",
            "IR-PXG40-GW",
            "IR-PXG40-GW-BLK",
            "IR-PXG40-LW",
            "IR-PXG40-LW-BLK",
            "IR-PXG40-PW",
            "IR-PXG40-PW-BLK",
            "IR-PXG40-SW",
            "IR-PXG40-SW-BLK",
            "IR-PXG41-5",
            "IR-PXG41-7",
            "IR-PXG41-8",
            "IR-PXG41-9",
            "IR-PXG41-PW",
            "KBS TOUR 130X",
            "PL3-ARMLOCK-HOS-BLK",
            "PL3-DOUBLEBEND-HOS-BLK",
            "PL3-H-HOS-BLK",
            "PL3-PLUMBERS-HOS-BLK",
            "PL4-BLACKBIRD-BLK",
            "PL4-BRANDON-BLK",
            "PL4-CLOSER-BLK",
            "PL4-DAGGER-BLK",
            "PL4-DAGGER-C-BLK",
            "PL4-HERCULES-BLK",
            "PL4-MUSTANG-BLK",
            "PL4-ONEDONE-BLK",
            "PL4-RAPTOR-BLK",
            "PL4-SPITFIRE-BLK",
            "PLASTIC LABELS -ELVTETOUR-S-STICKER",
            "PLASTIC LABELS-ELEVATEMP-95-R-STICKER",
            "PLASTIC LABELS-ELEVATEMP-95-S-STICKER",
            "PLASTIC PALLETS-EB",
            "PL-PXG5-APACHE-PLT",
            "PL-PXG5-BATATTACK-BLK",
            "PL-PXG5-BATATTACK-PLT",
            "PL-PXG5-BLACKJACK-BLK",
            "PL-PXG5-BLACKJACK-PLT",
            "PL-PXG5-BRANDON-BLK",
            "PL-PXG5-BRANDON-PLT",
            "PL-PXG5-CLOSER-BLK",
            "PL-PXG5-CLOSER-PLT",
            "PL-PXG5-DAGGER-PLT",
            "PL-PXG5-HERCULES-BLK",
            "PL-PXG5-HERCULES-PLT",
            "PL-PXG5-MUSTANG-PLT",
            "PL-PXG5-ONEDONE-PLT",
            "PL-PXG7-ALLAN-TU-BLK",
            "PR3-ARMLOCK-HOS-BLK",
            "PR3-DOUBLEBEND-HOS-BLK",
            "PR3-H-HOS-BLK",
            "PR3-PLUMBERS-HOS-BLK",
            "PR4-BATATTACK-BLK",
            "PR4-BLACKBIRD-BLK",
            "PR4-BLACKJACK-BLK",
            "PR4-BLACKJACK-C-BLK",
            "PR4-BRANDON-BLK",
            "PR4-CLOSER-BLK",
            "PR4-DAGGER-BLK",
            "PR4-DAGGER-C-BLK",
            "PR4-GUNBOAT-BLK",
            "PR4-HERCULES-BLK",
            "PR4-MUSTANG-BLK",
            "PR4-ONEDONE-BLK",
            "PR4-RAPTOR-BLK",
            "PR4-SPITFIRE-BLK",
            "PR5-BAYONET-BLK",
            "PR5-CLYDESDALE-BLK",
            "PR5-HELLCAT-BLK",
            "PR5-LIGHTNING-BLK",
            "PR5-V-42-BLK",
            "PR-PXG5-APACHE-PLT",
            "PR-PXG5-BATATTACK-BLK",
            "PR-PXG5-BATATTACK-C-PLT",
            "PR-PXG5-BATATTACK-PLT",
            "PR-PXG5-BLACKJACK-BLK",
            "PR-PXG5-BLACKJACK-C-PLT",
            "PR-PXG5-BLACKJACK-PLT",
            "PR-PXG5-BRANDON-BLK",
            "PR-PXG5-BRANDON-PLT",
            "PR-PXG5-CLOSER-BLK",
            "PR-PXG5-CLOSER-PLT",
            "PR-PXG5-DAGGER-C-PLT",
            "PR-PXG5-DAGGER-PLT",
            "PR-PXG5-HERCULES-BLK",
            "PR-PXG5-HERCULES-PLT",
            "PR-PXG5-MUSTANG-PLT",
            "PR-PXG5-ONEDONE-PLT",
            "PR-PXG7-ALLAN-TU-BLK",
            "PU3-CENTER-HOS-BLK",
            "S-ACCR-50I",
            "S-ACCR-60I",
            "S-ACCR-70I",
            "S-ACCR-80I",
            "S-AERO-70A-PARALLEL",
            "S-AERO-70R-PARALLEL",
            "S-AERO-95R-CW-4",
            "S-AERO-95R-CW-5",
            "S-AERO-95R-CW-6",
            "S-AERO-95R-CW-7",
            "S-AERO-95R-CW-8",
            "S-AERO-95R-CW-9",
            "S-AERO-95R-CW-WDG",
            "S-AERO-95S-CW-3",
            "S-AERO-95S-CW-4",
            "S-AERO-95S-CW-5",
            "S-AERO-95S-CW-6",
            "S-AERO-95S-CW-7",
            "S-AERO-95S-CW-8",
            "S-AERO-95S-CW-9",
            "S-AERO-BLKRSV-110S",
            "S-AERO-BLKRSV-60A",
            "S-AERO-BLKRSV-70R",
            "S-AERO-BLKRSV-95R",
            "S-AERO-BLKRSV-95S",
            "S-ALDI-NVGRN-65X-NXT",
            "S-ALDI-NVGRN-75X-NXT",
            "S-ALDI-NVGRN-HYB-85X",
            "S-ALDI-NVORG-HYB-85R",
            "S-ALDI-NVPNK-HYB-55L",
            "S-ALDI-NVSORG-55A-NXT",
            "S-DG-105R-37",
            "S-DG-105R-37.5",
            "S-DG-105R-38",
            "S-DG-105R-38.5",
            "S-DG-105R-39",
            "S-DG-105R-39.5",
            "S-DG-105R-40",
            "S-DG-105S-37",
            "S-DG-105S-37.5",
            "S-DG-105S-38",
            "S-DG-105S-38.5",
            "S-DG-105S-39",
            "S-DG-105S-39.5",
            "S-DG-105S-40",
            "S-DG-115S-37",
            "S-DG-120S-37",
            "S-DG-120S-37.5",
            "S-DG-120S-38",
            "S-DG-120S-38.5",
            "S-DG-120S-39",
            "S-DG-120S-39.5",
            "S-DG-120S-40",
            "S-DG-120X-37",
            "S-DG-120X-37.5",
            "S-DG-120X-38",
            "S-DG-120X-38.5",
            "S-DG-120X-39",
            "S-DG-120X-39.5",
            "S-DG-120X-40",
            "S-DG-95-R",
            "S-DG-95-S",
            "S-DG-MID-115-R",
            "S-DG-MID-115-S",
            "S-DG-MID-115-X",
            "S-DG-S400-9W",
            "S-DG-X100-3",
            "S-DG-X100-4",
            "S-DG-X100-5",
            "S-DG-X100-6",
            "S-DG-X100-7",
            "S-DG-X100-8",
            "S-DG-X100-9W",
            "S-DIAM-2023-SPLUS-60R",
            "S-DIAM-2023-SPLUS-60S",
            "S-DIAM-2023-SPLUS-60X",
            "S-DIAM-2023-SPLUS-70S",
            "S-DIAM-2023-SPLUS-70X",
            "S-DIAM-SPLUS-60R",
            "S-DIAM-SPLUS-60S",
            "S-DIAM-SPLUS-60X",
            "S-DIAM-SPLUS-70S",
            "S-DIAM-SPLUS-70X",
            "S-ELEVATE-95-R",
            "S-ELEVATE-95-S",
            "S-ELEVATEMP-95-R",
            "S-ELEVATEMP-95-S",
            "S-ELEV-TOUR-X-W",
            "S-ELVTETOUR-S-4",
            "S-ELVTETOUR-S-5",
            "S-ELVTETOUR-S-6",
            "S-ELVTETOUR-S-7",
            "S-ELVTETOUR-S-8",
            "S-ELVTETOUR-S-9",
            "S-ELVTETOUR-S-W",
            "S-ELVTETOUR-V2-S-3",
            "S-ELVTETOUR-V2-S-4",
            "S-ELVTETOUR-V2-S-5",
            "S-ELVTETOUR-V2-S-6",
            "S-ELVTETOUR-V2-S-7",
            "S-ELVTETOUR-V2-S-8",
            "S-ELVTETOUR-V2-S-9",
            "S-ELVTETOUR-V2-S-W",
            "S-ELVTETOUR-V2-X-3",
            "S-ELVTETOUR-V2-X-4",
            "S-ELVTETOUR-V2-X-5",
            "S-ELVTETOUR-V2-X-6",
            "S-ELVTETOUR-V2-X-7",
            "S-ELVTETOUR-V2-X-8",
            "S-ELVTETOUR-V2-X-9",
            "S-ELVTETOUR-V2-X-W",
            "S-ELVTETOUR-X-W",
            "S-FUBUKIV-40L",
            "S-FUBUKIV-40R",
            "S-FUBUKIV-50R",
            "S-FUJI-AIRSPD-40-R",
            "S-FUJI-AIRSPD-40-R2",
            "S-FUJI-MOTOREX-F3-5-R",
            "S-FUJI-MOTOREX-F3-5-R2",
            "S-FUJI-MOTOREX-F3-6-R",
            "S-FUJI-MOTOREX-F3-6-S",
            "S-FUJI-MOTOREX-F3-6-X",
            "S-FUJI-MOTOREX-F3-7-S",
            "S-FUJI-MOTOREX-F3-7-X",
            "S-FUJIPRO2.0-53-R",
            "S-FUJIPRO2.0-53-R2",
            "S-FUJIPRO2.0-63-R",
            "S-FUJIPRO2.0-63-R2",
            "S-FUJIPRO2.0-63R2-HY",
            "S-FUJIPRO2.0-63-X",
            "S-FUJIPRO2.0-73R-HY",
            "S-FUJIPRO2.0-73-S",
            "S-FUJIPRO2.0-73-X",
            "S-FUJIPRO2.0-83S-HY",
            "S-FUJIPRO2.0-83X-HY",
            "S-FUJI-VENTUS-5-R",
            "S-FUJI-VENTUS-6-S",
            "S-FUJI-VENTUS-6-X",
            "S-FUJI-VENTUS-7HB-R",
            "S-FUJI-VENTUS-7-S",
            "S-FUJI-VENTUS-7-X",
            "S-FUJI-VENTUS-8HB-S",
            "S-FUJI-VENTUS-9HB-X",
            "S-FUJI-VENTUSBLK-6-S",
            "S-FUJI-VENTUSBLK-6-X",
            "S-FUJI-VENTUSBLK-7-S",
            "S-FUJI-VENTUSBLK-7-X",
            "S-FUJI-VENTUSRED-5-R",
            "S-FUJI-VENTUSRED-5-R2",
            "S-FUJI-VNTS-VCP-BLU-5-R",
            "S-FUJI-VNTS-VCP-BLU-5-S",
            "S-FUJI-VNTS-VCP-BLU-6-S",
            "S-FUJI-VNTS-VCP-BLU-6-X",
            "S-FUJI-VNTS-VCP-BLU-7-S",
            "S-FUJI-VNTS-VCP-BLU-7-X",
            "S-GRANDBASSARA-29-L",
            "S-KBS-CTPER120-3",
            "S-KBS-CTPER120-4",
            "S-KBS-CTPER120-5",
            "S-KBS-CTPER120-6",
            "S-KBS-CTPER120-7",
            "S-KBS-CTPER120-8",
            "S-KBS-CTPER120-9W",
            "S-KBS-CTPER130-3",
            "S-KBS-CTPER130-4",
            "S-KBS-CTPER130-5",
            "S-KBS-CTPER130-6",
            "S-KBS-CTPER130-7",
            "S-KBS-CTPER130-8",
            "S-KBS-CTPER130-9W",
            "S-KBS-CTPERLITE110",
            "S-KBS-CTPERLITE110-3",
            "S-KBS-CTPERLITE110-4",
            "S-KBS-CTPERLITE110-5",
            "S-KBS-CTPERLITE110-6",
            "S-KBS-CTPERLITE110-7",
            "S-KBS-CTPERLITE110-8",
            "S-KBS-CTPERLITE110-9",
            "S-KBS-HIREV2-R",
            "S-KBS-MAXGRPH-45-L-IRON",
            "S-KBS-MAXGRPH-55-A-IRON",
            "S-KBS-MAXGRPH-65-R-IRON",
            "S-KBS-STAPER-LITE-R",
            "S-KBS-STAPER-LITE-S",
            "S-KBS-STPERLITE115-S-3",
            "S-KBS-STPERLITE115-S-4",
            "S-KBS-STPERLITE115-S-5",
            "S-KBS-STPERLITE115-S-6",
            "S-KBS-STPERLITE115-S-7",
            "S-KBS-STPERLITE115-S-8",
            "S-KBS-STPERLITE115-S-9W",
            "S-KBS-STPERLITE95-9IR/WDG",
            "S-KBS-STPERLITE95-9W",
            "S-KBS-TOUR-110-3",
            "S-KBS-TOUR-110-4",
            "S-KBS-TOUR-110-5",
            "S-KBS-TOUR-110-6",
            "S-KBS-TOUR-110-7",
            "S-KBS-TOUR-110-8",
            "S-KBS-TOUR-110-9W",
            "S-KBS-TOUR-120-3",
            "S-KBS-TOUR-120-4",
            "S-KBS-TOUR-120-5",
            "S-KBS-TOUR-120-6",
            "S-KBS-TOUR-120-7",
            "S-KBS-TOUR-120-8",
            "S-KBS-TOUR-120-9W",
            "S-KBS-TOUR-130-3",
            "S-KBS-TOUR-130-4",
            "S-KBS-TOUR-130-5",
            "S-KBS-TOUR-130-6",
            "S-KBS-TOUR-130-7",
            "S-KBS-TOUR-130-8",
            "S-KBS-TOUR-130-9W",
            "S-KBS-TOUR-50L",
            "S-KBS-TOUR-70R",
            "S-KBS-TOUR-80S",
            "S-KBS-TOUR-85H-S",
            "S-KBS-TOUR-95H-X",
            "S-KBS-TOUR-LITE-R",
            "S-KBS-TOUR-LITE-S",
            "S-KBS-TOUR-LITE-X",
            "S-KUROKAGE-BLK-45L",
            "S-KUROKAGE-BLK-55A",
            "S-KUROKAGE-BLK-55R",
            "S-KUROKAGE-BLK-55S",
            "S-MMT-50-L",
            "S-MMT-60-A",
            "S-MMT-70-R",
            "S-MMT-80-S",
            "S-MMT-TAPER-105-S-3",
            "S-MMT-TAPER-105-S-4",
            "S-MMT-TAPER-105-S-5",
            "S-MMT-TAPER-105-S-6",
            "S-MMT-TAPER-105-S-7",
            "S-MMT-TAPER-105-S-8",
            "S-MMT-TAPER-105-S-9",
            "S-MMT-TAPER-105-S-W",
            "S-MMT-TAPER-125-X-3",
            "S-MMT-TAPER-125-X-4",
            "S-MMT-TAPER-125-X-5",
            "S-MMT-TAPER-125-X-6",
            "S-MMT-TAPER-125-X-7",
            "S-MMT-TAPER-125-X-8",
            "S-MMT-TAPER-125-X-9",
            "S-MMT-TAPER-125-X-W",
            "S-NIP-850GH-R-9",
            "S-NIP-950GH-R-3",
            "S-NIP-950GH-R-4",
            "S-NIP-950GH-R-5",
            "S-NIP-950GH-R-6",
            "S-NIP-950GH-R-7",
            "S-NIP-950GH-R-8",
            "S-NIP-950GH-R-9",
            "S-NIP-950GH-R-PW",
            "S-NIP-950GH-S-3",
            "S-NIP-950GH-S-4",
            "S-NIP-950GH-S-5",
            "S-NIP-950GH-S-6",
            "S-NIP-950GH-S-7",
            "S-NIP-950GH-S-8",
            "S-NIP-950GH-S-9",
            "S-NIP-950GH-S-PW",
            "S-NIP-MODPRO-105R-3",
            "S-NIP-MODPRO-105R-4",
            "S-NIP-MODPRO-105R-5",
            "S-NIP-MODPRO-105R-6",
            "S-NIP-MODPRO-105R-7",
            "S-NIP-MODPRO-105R-8",
            "S-NIP-MODPRO-105R-9",
            "S-NIP-MODPRO-105R-W",
            "S-NIP-MODPRO-105S-3",
            "S-NIP-MODPRO-105S-4",
            "S-NIP-MODPRO-105S-5",
            "S-NIP-MODPRO-105S-6",
            "S-NIP-MODPRO-105S-7",
            "S-NIP-MODPRO-105S-8",
            "S-NIP-MODPRO-105S-9",
            "S-NIP-MODPRO-105S-PW",
            "S-NIP-MODPRO-120S-3",
            "S-NIP-MODPRO-120S-4",
            "S-NIP-MODPRO-120S-5",
            "S-NIP-MODPRO-120S-6",
            "S-NIP-MODPRO-120S-7",
            "S-NIP-MODPRO-120S-8",
            "S-NIP-MODPRO-120S-9",
            "S-NIP-MODPRO-120S-PW",
            "S-NIP-MODPRO-120X-2",
            "S-NIP-MODPRO-120X-3",
            "S-NIP-MODPRO-120X-4",
            "S-NIP-MODPRO-120X-5",
            "S-NIP-MODPRO-120X-6",
            "S-NIP-MODPRO-120X-7",
            "S-NIP-MODPRO-120X-8",
            "S-NIP-MODPRO-120X-9",
            "S-NIP-MODPRO-120X-PW",
            "S-PROJX-CYPHER-40-4.0",
            "S-PROJX-CYPHER-40-5.0",
            "S-PROJX-CYPHER-40-5.5",
            "S-PROJX-CYPHER-40I-4.0",
            "S-PROJX-CYPHER-50-5.5",
            "S-PROJX-CYPHER-50-6.0",
            "S-PROJX-CYPHER-50I-5.0",
            "S-PROJX-CYPHER-60I-5.5",
            "S-PROJX-HZRDBLK-G4-60-6.0",
            "S-PROJX-HZRDBLK-G4-60-6.5",
            "S-PROJX-HZRDBLK-G4-70-6.0",
            "S-PROJX-HZRDBLK-G4-70-6.5",
            "S-PROJX-HZRDSMK-B-HYB-S",
            "S-PROJX-HZRDSMK-B-HYB-X",
            "S-PROJX-HZRDSMK-Y-60-X",
            "S-PROJX-HZRDSMK-Y-70-S",
            "S-PROJX-SMKRDX-BLK-60-6.0",
            "S-PROJX-SMKRDX-BLK-70-6.0",
            "S-PROJX-SMKRDX-BLK-70-6.5",
            "S-PROJX-SMKRDX-HYB-BLK-80-6.0",
            "S-PROJX-SMKRDX-HYB-BLK-90-6.5",
            "S-PX-6.5-37",
            "S-PX-6.5-37.5",
            "S-PX-6.5-38",
            "S-PX-6.5-38.5",
            "S-PX-6.5-39",
            "S-PX-6.5-39.5",
            "S-PX-6.5-40",
            "S-PX-6.5-40.5",
            "S-PX-CYPHER2.0-40-4.0",
            "S-PX-CYPHER2.0-40-5.0",
            "S-PX-CYPHER2.0-40-5.5",
            "S-PX-CYPHER2.0-40I-4.0",
            "S-PX-CYPHER2.0-50-5.5",
            "S-PX-CYPHER2.0-50-6.0",
            "S-PX-CYPHER2.0-50I-5.0",
            "S-PX-CYPHER2.0-60I-5.5",
            "S-PX-DENALI-BLU-50-5.0",
            "S-PX-DENALI-BLU-50-5.5",
            "S-PX-DENALI-BLU-50-6.0",
            "S-PX-DENALI-BLU-60-5.5",
            "S-PX-DENALI-BLU-60-6.0",
            "S-PX-DENALI-BLU-60-6.5",
            "S-PX-DENALI-BLU-70-6.5",
            "S-PX-DENALI-BLU-HYB-80-5.5",
            "S-PX-DENALI-BLU-HYB-80-6.0",
            "S-PX-DENALI-BLU-HYB-80-6.5",
            "S-PXG-MMPS01-DB",
            "S-PXG-MMPS01-DB-BLK",
            "S-PXG-MMPS01-STR",
            "S-PXG-MMPS01-STR-BLK",
            "S-PXG-PUTT-2BEND-CHR",
            "S-PXG-PUTT-STRAIGHT-CHR",
            "S-PX-LZ-6.0-36.5",
            "S-PX-LZ-6.0-37",
            "S-PX-LZ-6.0-37.5",
            "S-PX-LZ-6.0-38",
            "S-PX-LZ-6.0-38.5",
            "S-PX-LZ-6.0-39",
            "S-PX-LZ-6.0-39.5",
            "S-PX-LZ-6.0-40",
            "S-PX-LZ-6.5-36.5",
            "S-PX-LZ-6.5-37",
            "S-PX-LZ-6.5-37.5",
            "S-PX-LZ-6.5-38",
            "S-PX-LZ-6.5-38.5",
            "S-PX-LZ-6.5-39",
            "S-PX-LZ-6.5-39.5",
            "S-PX-LZ-6.5-40",
            "STAPER LITE R",
            "S-TENSEIAV-HYB-WHT-85-S",
            "S-TENSEIAV-RAW-B-55-A",
            "S-TENSEIAV-RAW-B-55-R",
            "S-TENSEIAV-RAW-B-65-R",
            "S-TENSEIAV-RAW-B-65-S",
            "S-TENSEIAV-RAW-B-75-S",
            "S-TENSEIAV-RAW-HYB-B-75-R",
            "S-TENSEIAV-RAW-HYB-B-75-S",
            "S-TENSEIAV-RAW-O-55-R",
            "S-TENSEIAV-RAW-O-55-S",
            "S-TENSEIAV-RAW-O-55-X",
            "S-TENSEIAV-RAW-W-65-X",
            "S-TENSEIAV-RAW-W-75-X",
            "S-TENSEIAV-WHT-65-S",
            "S-TENSEIAV-WHT-75-S",
            "S-TENSEIAV-XLNK-BLU-55-R",
            "S-TENSEIAV-XLNK-BLU-65-R",
            "S-TENSEIAV-XLNK-BLU-65-S",
            "S-TENSEIAV-XLNK-BLU-75-S",
            "S-TENSEIAV-XLNK-HYB-BLU-75-R",
            "S-TENSEIAV-XLNK-HYB-BLU-75-S",
            "S-TENSEIAV-XLNK-HYB-WHT-85-X",
            "S-TENSEIAV-XLNK-WHT-65-S",
            "S-TENSEIAV-XLNK-WHT-65-X",
            "S-TENSEIAV-XLNK-WHT-75-S",
            "S-TENSEIAV-XLNK-WHT-75-X",
            "S-TENSEI-CKPRO-B-80R",
            "S-TENSEI-CKPRO-B-80S",
            "S-TOURAD-DI-HYB-85S",
            "S-TOURAD-DI-HYB-85X",
            "S-TOURAD-GP7-X",
            "S-TOURAD-GP8-X",
            "S-TOURAD-HD4-R2",
            "S-TOURAD-HD5-R",
            "S-TOURAD-HD5-S",
            "S-TOURAD-IZ-5R1",
            "S-TOURAD-IZ-5R2",
            "S-TOURAD-IZ-HYB-6R2",
            "S-TOURAD-IZ-HYB-7R",
            "S-TOURAD-TP5-R",
            "S-TOURAD-TP5-S",
            "S-TOURAD-TP6-S",
            "S-TOURAD-TP6-X",
            "S-TOURAD-TP7-S",
            "S-TOURAD-TP7-X",
            "S-TOURAD-TP8-X",
            "S-TOURAD-UB-5-R",
            "S-TOURAD-UB-5-S",
            "S-TOURAD-UB-6-S",
            "S-TOURAD-VF-5-S",
            "S-TOURAD-VF-5-X",
            "S-TOURAD-VF-6-S",
            "S-TOURAD-VF-6-X",
            "S-TOURAD-VF-7-S",
            "S-TOURAD-VF-7-X",
            "S-TOURAD-VR-5-R",
            "S-TOURAD-VR-6-S",
            "S-TOURAD-VR-7-S",
            "S-TOURAD-XC-4-R2",
            "S-TOURAD-XC-5-R",
            "S-TOURAD-XC-5-S",
            "S-TOURAD-XC-6-S",
            "S-TOURAD-XC-6-X",
            "S-TOURAD-XC-7-X",
            "S-TT-RIPTIDE-CB-40-4.0",
            "S-TT-RIPTIDE-CB-40-5.0",
            "S-TT-RIPTIDE-CB-50-5.0",
            "S-TT-RIPTIDE-CB-50-5.5",
            "S-TT-RIPTIDE-CB-50-6.0",
            "S-TT-RIPTIDE-CB-60-5.5",
            "S-TT-RIPTIDE-CB-60-6.0",
            "S-TT-RIPTIDE-HYB-85-5.5",
            "S-TT-RIPTIDE-HYB-85-6.0",
            "S-TT-RIPTIDE-HYB-85-6.5",
            "S-USTM-HELBLK-5-F4",
            "S-USTM-RECDART-55F1-L",
            "S-USTM-RECDART-65F2-A",
            "S-USTM-RECDART-75F3-R",
            "S-USTM-RECDART-75F4-S",
            "TORQUE-CARD-MARKETING-CA",
            "TT-DG-S-400-SS",
            "TT-DG-X-100-SS",
            "WL-PXG5-50-10-BLK",
            "WL-PXG5-50-10-CHR",
            "WL-PXG5-50-13-BLK",
            "WL-PXG5-50-13-CHR",
            "WL-PXG5-52-10-BLK",
            "WL-PXG5-52-10-CHR",
            "WL-PXG5-52-13-BLK",
            "WL-PXG5-52-13-CHR",
            "WL-PXG5-54-10-BLK",
            "WL-PXG5-54-10-CHR",
            "WL-PXG5-54-13-BLK",
            "WL-PXG5-54-13-CHR",
            "WL-PXG5-56-10-BLK",
            "WL-PXG5-56-10-CHR",
            "WL-PXG5-56-13-BLK",
            "WL-PXG5-56-13-CHR",
            "WL-PXG5-58-10-BLK",
            "WL-PXG5-58-10-CHR",
            "WL-PXG5-58-13-BLK",
            "WL-PXG5-58-13-CHR",
            "WL-PXG5-60-10-BLK",
            "WL-PXG5-60-10-CHR",
            "WL-PXG5-60-13-BLK",
            "WL-PXG5-60-13-CHR",
            "WL-PXG5-62-10-BLK",
            "WL-PXG5-62-10-CHR",
            "WL-PXG5-62-13-CHR",
            "WL-PXG6-50-BLK",
            "WL-PXG6-50-CHR",
            "WL-PXG6-52-BLK",
            "WL-PXG6-52-CHR",
            "WL-PXG6-54-BLK",
            "WL-PXG6-54-CHR",
            "WL-PXG6-56-BLK",
            "WL-PXG6-56-CHR",
            "WL-PXG6-58-BLK",
            "WL-PXG6-58-CHR",
            "WL-PXG6-60-BLK",
            "WL-PXG6-60-CHR",
            "WL-PXG6-62-BLK",
            "WL-PXG6-62-CHR",
            "WL-PXG7-BLK-50-10S",
            "WL-PXG7-BLK-52-10S",
            "WL-PXG7-BLK-54-10S",
            "WL-PXG7-BLK-54-12BP",
            "WL-PXG7-BLK-56-10S",
            "WL-PXG7-BLK-56-12BP",
            "WL-PXG7-BLK-58-10S",
            "WL-PXG7-BLK-58-12BP",
            "WL-PXG7-BLK-60-10S",
            "WL-PXG7-BLK-60-12BP",
            "WL-PXG7-CHR-50-10S",
            "WL-PXG7-CHR-52-10S",
            "WL-PXG7-CHR-54-10S",
            "WL-PXG7-CHR-54-12BP",
            "WL-PXG7-CHR-56-10S",
            "WL-PXG7-CHR-56-12BP",
            "WL-PXG7-CHR-58-10S",
            "WL-PXG7-CHR-58-12BP",
            "WL-PXG7-CHR-60-10S",
            "WL-PXG7-CHR-60-12BP",
            "WR-PXG3-52-CHR",
            "WR-PXG3-56-CHR",
            "WR-PXG3-60-7-CHR",
            "WR-PXG3-62-CHR",
            "WR-PXG4-54-CHR",
            "WR-PXG4-56-CHR",
            "WR-PXG4-58-CHR",
            "WR-PXG4-60-CHR",
            "WR-PXG5-50-10-BLK",
            "WR-PXG5-50-10-CHR",
            "WR-PXG5-50-13-BLK",
            "WR-PXG5-50-13-CHR",
            "WR-PXG5-52-10-BLK",
            "WR-PXG5-52-10-CHR",
            "WR-PXG5-52-13-BLK",
            "WR-PXG5-52-13-CHR",
            "WR-PXG5-54-10-BLK",
            "WR-PXG5-54-10-CHR",
            "WR-PXG5-54-13-BLK",
            "WR-PXG5-54-13-CHR",
            "WR-PXG5-56-10-BLK",
            "WR-PXG5-56-10-CHR",
            "WR-PXG5-56-13-BLK",
            "WR-PXG5-56-13-CHR",
            "WR-PXG5-58-10-BLK",
            "WR-PXG5-58-10-CHR",
            "WR-PXG5-58-13-BLK",
            "WR-PXG5-58-13-CHR",
            "WR-PXG5-60-10-BLK",
            "WR-PXG5-60-10-CHR",
            "WR-PXG5-60-13-BLK",
            "WR-PXG5-60-13-CHR",
            "WR-PXG5-62-10-BLK",
            "WR-PXG5-62-10-CHR",
            "WR-PXG5-62-13-BLK",
            "WR-PXG5-62-13-CHR",
            "WR-PXG6-50-BLK",
            "WR-PXG6-50-CHR",
            "WR-PXG6-52-BLK",
            "WR-PXG6-52-CHR",
            "WR-PXG6-54-BLK",
            "WR-PXG6-54-CHR",
            "WR-PXG6-56-BLK",
            "WR-PXG6-56-CHR",
            "WR-PXG6-58-BLK",
            "WR-PXG6-58-CHR",
            "WR-PXG6-60-BLK",
            "WR-PXG6-60-CHR",
            "WR-PXG6-62-BLK",
            "WR-PXG6-62-CHR",
            "WR-PXG7-BLK-50-10S",
            "WR-PXG7-BLK-52-10S",
            "WR-PXG7-BLK-54-10S",
            "WR-PXG7-BLK-54-12BP",
            "WR-PXG7-BLK-56-10S",
            "WR-PXG7-BLK-58-07C",
            "WR-PXG7-BLK-58-10S",
            "WR-PXG7-BLK-58-12BP",
            "WR-PXG7-BLK-60-07C",
            "WR-PXG7-BLK-60-10S",
            "WR-PXG7-BLK-60-12BP",
            "WR-PXG7-CHR-50-10S",
            "WR-PXG7-CHR-52-10S",
            "WR-PXG7-CHR-54-10S",
            "WR-PXG7-CHR-54-12BP",
            "WR-PXG7-CHR-56-10S",
            "WR-PXG7-CHR-56-12BP",
            "WR-PXG7-CHR-58-07C",
            "WR-PXG7-CHR-58-10S",
            "WR-PXG7-CHR-58-12BP",
            "WR-PXG7-CHR-60-07C",
            "WR-PXG7-CHR-60-10S",
            "WR-PXG7-CHR-60-12BP",
            "B-PG-172-BGRY-MS",
            "B-PG-172-DB-MS",
            "B-PG-172-WBLK-MS",
            "IL-PXG41-4",
            "IL-PXG41-5",
            "IL-PXG41-6",
            "IL-PXG41-7",
            "IL-PXG41-8",
            "IL-PXG41-9",
            "IL-PXG41-GW",
            "IL-PXG41-LW",
            "IL-PXG41-PW",
            "IL-PXG41-SW",
            "IR-PXG41-4",
            "IR-PXG41-6",
            "IR-PXG41-GW",
            "IR-PXG41-LW",
            "IR-PXG41-SW",
            "S-TENSEIAV-XLNK-HYB-WHT-85-S",
            "WR-PXG7-BLK-56-12BP",
            "B-PG-172SS-MS",
            "B-PG-173-BGRY-MS",
            "H-23PXG000166-BLK-OSFM-MS",
            "H-23PXG000166-WHT-OSFM-MS",
            "H-60362025-MS",
            "GB-DOZ-XTTR-WHT-MS",
            "GB-DOZ-XTTRX-WHT-MS",
            "B-PG-173-BO-MS",
            "B-PG-173-WBLK-MS",
            "B-UGB14-FM-MS",
            "GB-DOZ-XTTR-YEL-MS",
            "IR-PXG30-4",
            "B-PG-173-WO-MS",
            "B-PG-173-BGRY",
            "GB-DOZ-XTTR-YEL",
            "GB-DOZ-XTTRX-WHT",
            "B-PG-172-BLACK-MS",
            "B-PG-172-GREEN-MS",
            "B-PG-172-GREY-MS",
            "B-PG-172-NAVY-MS",
            "B-PG-172-TAN-MS",
            "G-PXG-PG-SLT-1.5-L-BLK",
            "G-PXG-PG-SLT-1.5-R-BLK",
            "IR-PXG42-DC-RAW",
            "B-PG-172-BGRY",
            "PL-PXG8-BRANDON-P-GNM",
            "PL-PXG8-BRANDONII-P-GNM",
            "PR-PXG8-BRANDONII-P-GNM",
            "PR-PXG8-BRANDON-P-GNM",
            "HC-JT-4623",
            "S-PX-DENALI-RED-60-5.5",
            "DL-PXG25-13",
            "DL-PXG27-1",
            "DR-PXG25-13",
            "DR-PXG27-1",
            "FL-PXG16-5",
            "FR-PXG16-5",
            "HC-1322-WCDR",
            "HC-1342-SWDR",
            "HC-1352-WCFW5",
            "HC-1353-WCHY6",
            "HL-PXG16-6",
            "HR-PXG16-6",
            "IL-PXG42-DC-RAW",
            "IL-PXG43-7",
            "IL-PXG43-8",
            "IL-PXG43-9",
            "IL-PXG43-PW",
            "IL-PXG43-SW",
            "IR-PXG43-7",
            "IR-PXG43-8",
            "IR-PXG43-9",
            "IR-PXG43-PW",
            "IR-PXG43-SW",
            "PL-PXG6-BLACKHAWK-BLK",
            "PR-PXG6-BLACKHAWK-BLK",
            "A-1IBM65819PXGCAT-MS",
            "A-1IBM65820PXG-DT-MS",
            "A-ALIGNSTICKS-WHT-MS",
            "A-DARKNESS-COASTER-MS",
            "A-DUO-PXG-MS",
            "A-ICU55715PXG-ALS-MS",
            "A-IHC62918PXG-COP-MS",
            "A-IHC62920PXG-BLK-MS",
            "A-JT-4697-MS",
            "A-NX10SLOPE-PXG-MS",
            "A-Q23192-ASM-2-MS",
            "A-Q25240-ASM-MS",
            "A-UAC17-FM-MS",
            "A-UAC18-FM-MS",
            "A-UAC28-FM-MS",
            "A-UAC29-FM-MS",
            "A-ZNP53374-1-MS",
            "G4-652011019RHL-BLK-MS",
            "G4-652011019RHSC-BLK-MS",
            "H-22PXG000013-BLK-MS",
            "H-22PXG000013-WHT-MS",
            "H-23PXG0000124-2-BG-OSFM-MS",
            "H-23PXG0000124-2-BW-OSFM-MS",
            "H-23PXG0000124-2-GB-OSFM-MS",
            "H-23PXG0000124-2-WG-OSFM-MS",
            "H-23PXG000078-1-L-XL-MS",
            "H-23PXG000078-1-S-M-MS",
            "H-23PXG000094-1-OSFM-BLK-MS",
            "H-23PXG000094-1-OSFM-WHT-MS",
            "H-23PXG000101-BW-OSFM-MS",
            "H-23PXG000101-NW-OSFM-MS",
            "H-23PXG000101-WB-OSFM-MS",
            "H-23PXG000123-BG-OSFM-MS",
            "H-23PXG000123-BW-OSFM-MS",
            "H-23PXG000123-GB-OSFM-MS",
            "H-23PXG000123-WG-OSFM-MS",
            "H-23PXG000125-BG-OSFM-MS",
            "H-23PXG000125-BW-OSFM-MS",
            "H-23PXG000125-GB-OSFM-MS",
            "H-23PXG000125-NW-OSFM-MS",
            "H-23PXG000125-WG-OSFM-MS",
            "H-23PXG000125-WN-OSFM-MS",
            "H-23PXG000167-BW-OSFM-MS",
            "H-23PXG000167-GB-OSFM-MS",
            "H-23PXG000167-WB-OSFM-MS",
            "H-23PXG000167-WW-OSFM-MS",
            "H-23PXG000168-BLK-OSFM-MS",
            "H-23PXG000168-GRY-OSFM-MS",
            "H-23PXG000168-NVY-OSFM-MS",
            "H-23PXG000168-WHT-OSFM-MS",
            "H-24PXG000203-2-BLK-OSFM-MS",
            "H-24PXG000203-2-WHT-OSFM-MS",
            "H-24PXG000219-OSFM-MS",
            "H-24PXG000229-OSFM-MS",
            "H-24PXG000235-BW-OSFM-MS",
            "H-24PXG000235-GB-OSFM-MS",
            "H-24PXG000235-WG-OSFM-MS",
            "H-24PXG000239-OSFM-MS",
            "H-USMC-ADJ-MS",
            "HC-1310-DRKTIKIMAL",
            "HC-JT-1053-KIT",
            "S-KBS-TOUR-PVD-110-R-4",
            "S-KBS-TOUR-PVD-110-R-5",
            "S-KBS-TOUR-PVD-110-R-6",
            "S-KBS-TOUR-PVD-110-R-7",
            "S-KBS-TOUR-PVD-110-R-8",
            "S-KBS-TOUR-PVD-110-R-9W",
            "S-KBS-TOUR-PVD-120-S-3",
            "S-KBS-TOUR-PVD-120-S-4",
            "S-KBS-TOUR-PVD-120-S-5",
            "S-KBS-TOUR-PVD-120-S-6",
            "S-KBS-TOUR-PVD-120-S-7",
            "S-KBS-TOUR-PVD-120-S-8",
            "S-KBS-TOUR-PVD-120-S-9W",
            "S-KBS-TOUR-PVD-130-X-3",
            "S-KBS-TOUR-PVD-130-X-4",
            "S-KBS-TOUR-PVD-130-X-5",
            "S-KBS-TOUR-PVD-130-X-6",
            "S-KBS-TOUR-PVD-130-X-7",
            "S-KBS-TOUR-PVD-130-X-8",
            "S-KBS-TOUR-PVD-130-X-9W",
            "S-PX-DENALI-RED-50-5.0",
            "S-PX-DENALI-RED-50-5.5",
            "S-PX-DENALI-RED-50-6.0",
            "T-IRON-FITTING-SLEEV",
            "A-NX10SLOPE-PXG",
            "B-PG-172-GREY",
            "B-PG-173-WO",
            "H-23PXG000094-1-OSFM-WHT",
            "H-23PXG000166-BLK-OSFM",
            "H-23PXG000166-WHT-OSFM",
            "B-PG-244-MS",
            "B-PG-245-BLK-MS",
            "B-PG-245-WHT-MS",
            "DR-PXG29-10.5",
            "DR-PXG29-11.5",
            "H-MONM-NAT-ML-MS",
            "HC-1308-25ALBLD",
            "S-ACCR-ISTL-GRN-105-R",
            "S-ACCR-ISTL-GRN-115-S",
            "S-ACCR-ISTL-GRN-125-X-4",
            "S-ACCR-ISTL-GRN-125-X-5",
            "S-ACCR-ISTL-GRN-125-X-6",
            "S-ACCR-ISTL-GRN-125-X-7",
            "S-ACCR-ISTL-GRN-125-X-8",
            "S-ACCR-ISTL-GRN-125-X-9W",
            "S-PX-HZRDG5-BLK-70-6.0",
            "S-ACCR-ISTL-GRN-125-X-9",
            "S-FUJI-24PRO-BLU-50-R",
            "S-FUJI-24PRO-BLU-60-S",
            "S-FUJI-24PRO-BLU-60-X",
            "S-FUJI-24PRO-BLU-70-S",
            "S-FUJI-24PRO-BLU-70-X",
            "S-FUJI-VNTS-VCP-BLK-6-S",
            "S-FUJI-VNTS-VCP-BLK-6-X",
            "S-FUJI-VNTS-VCP-BLK-7-S",
            "S-FUJI-VNTS-VCP-BLK-7-X",
            "S-PX-HZRDG5-BLK-60-6.5",
            "G4-652011019LHL-BLK-MS",
            "G4-652011019LHLC-BLK-MS",
            "G4-652011019LHLW-BLK-MS",
            "G4-652011019LHM-BLK-MS",
            "G4-652011019LHMC-BLK-MS",
            "G4-652011019LHML-BLK-MS",
            "G4-652011019LHMLC-BLK-MS",
            "G4-652011019LHMW-BLK-MS",
            "G4-652011019LHS-BLK-MS",
            "G4-652011019LHSC-BLK-MS",
            "G4-652011019LHSW-BLK-MS",
            "G4-652011019LHXL-BLK-MS",
            "G4-652011019LHXLC-BLK-MS",
            "G4-652011019RHLC-BLK-MS",
            "G4-652011019RHM-BLK-MS",
            "G4-652011019RHMC-BLK-MS",
            "G4-652011019RHML-BLK-MS",
            "G4-652011019RHMLC-BLK-MS",
            "G4-652011019RHS-BLK-MS",
            "G4-652011019RHXL-BLK-MS",
            "G4-652011019RHXLC-BLK-MS",
            "G4-652011019RHXXL-BLK-MS",
            "G4-652021019LHL-WHT-MS",
            "G4-652021019LHLC-WHT-MS",
            "G4-652021019LHLW-WHT-MS",
            "G4-652021019LHM-WHT-MS",
            "G4-652021019LHMC-WHT-MS",
            "G4-652021019LHML-WHT-MS",
            "G4-652021019LHMLC-WHT-MS",
            "G4-652021019LHMW-WHT-MS",
            "G4-652021019LHS-WHT-MS",
            "G4-652021019LHSC-WHT-MS",
            "G4-652021019LHSW-WHT-MS",
            "G4-652021019LHXL-WHT-MS",
            "G4-652021019LHXLC-WHT-MS",
            "G4-652021019LHXXL-WHT-MS",
            "G4-652021019RHL-WHT-MS",
            "G4-652021019RHLC-WHT-MS",
            "G4-652021019RHLW-WHT-MS",
            "G4-652021019RHM-WHT-MS",
            "G4-652021019RHMC-WHT-MS",
            "G4-652021019RHML-WHT-MS",
            "G4-652021019RHMLC-WHT-MS",
            "G4-652021019RHMW-WHT-MS",
            "G4-652021019RHS-WHT-MS",
            "G4-652021019RHSC-WHT-MS",
            "G4-652021019RHSW-WHT-MS",
            "G4-652021019RHXL-WHT-MS",
            "G4-652021019RHXLC-WHT-MS",
            "G4-652021019RHXXL-WHT-MS",
            "H-24PXG000214-1-BLK-OSFM-MS",
            "H-24PXG000214-1-WHT-OSFM-MS",
            "H-24PXG000218-1-OSFM-MS",
            "S-ACCR-ISTL-GRN-125-X-W",
            "B-PG-172-WBLK",
            "HC-1307-25ALMAL",
            "S-FUJI-24PRO-BLU-50-R2",
            "S-FUJI-24PRO-BLU-60-R",
            "S-FUJI-VNTS-VCP-RED-5-R",
            "S-FUJI-VNTS-VCP-RED-5-R2",
            "S-PX-DENALI-RED-40-4.0",
            "S-PX-DENALI-RED-60-6.0",
            "S-PX-HZRDG5-BLK-60-6.0",
            "S-PX-HZRDG5-BLK-80-6.5",
            "H-USMC-ADJ",
            "B-PG-246-POLY-MS",
            "H-22PXG000014-BLK-MS",
            "H-22PXG000014-WHT-MS",
            "S-PX-HZRDG5-BLK-70-6.5",
            "S-FUJI-VNTS-VCP-RED-5-S",
            "S-FUJI-VNTS-VCP-RED-6-S",
            "GB-DOZ-XTTR-WHT",
            "G-WINN-EXCEL-OVR-BLK",
            "S-KBS-STPERLITE100-S-3",
            "S-KBS-STPERLITE100-S-4",
            "S-KBS-STPERLITE100-S-5",
            "S-KBS-STPERLITE100-S-6",
            "S-KBS-STPERLITE100-S-7",
            "S-KBS-STPERLITE100-S-8",
            "S-KBS-STPERLITE100-S-9W",
            "IR-PXG36-SW",
            "IR-PXG36-SW-BLK",
            "PL-PXG7-BATATTACK-BLK",
            "PR-PXG7-BATATTACK-BLK",
            "B-PG-081-BLK-MS",
            "B-PG-172-DKNSS-MS",
            "B-PG-173-DKNSS-MS",
            "A-Q25645-ASM-1-MS",
            "B-PG-172-MS",
            "B-PG-173-MS",
            "B-PG-245-MS",
            "H-24PXG000276-OSFM-MS",
            "H-24PXG000277-OSFM-MS",
            "H-24PXG000278-OSFM-MS",
            "H-25PXG000282-OSFM-MS",
            "H-25PXG000283-OSFM-MS",
            "HC-1354-25SSDR",
            "HC-1356-25SSBLD",
            "HC-1360-25SSMAL",
            "PL-PXG7-ALLAN-XDRK",
            "PR-PXG7-ALLAN-XDRK",
            "B-UGB1-EP-MS",
            "B-UGB13-EP-B-MS",
            "B-UGB2-EP-MS",
            "PL-PXG6-HELLCAT-ZTB-SS",
            "PR-PXG6-HELLCAT-ZTB-SS",
            "S-PXG-IRON-STEEL",
            "B-PG-172-WHTBLK-MS",
            "B-PG-173-WHTBLK-MS",
            "PB-PAD-XP1-BLK-MS",
            "PB-PAD-XP2-BLK-MS",
            "PL-PXG5-TORPEDO-BLK",
            "PR-PXG5-TORPEDO-BLK",
            "PR-PXG8-FATBRANDON-P-GNM",
            "HC-JT-4831",
            "PR-PXG7-MUSTANG-BLK",
            "PL-PXG7-MUSTANG-BLK",
            "HC-1349-RLBLD",
            "G-TT-ICON-PXG-STD-BLK",
            "DL-PXG31-10.5",
            "DL-PXG31-12",
            "DL-PXG31-9",
            "DL-PXG33-9",
            "DL-PXG34-11.5",
            "DR-PXG31-10.5",
            "DR-PXG31-12",
            "DR-PXG31-9",
            "DR-PXG32-10.5",
            "DR-PXG32-8",
            "DR-PXG32-9",
            "DR-PXG33-10.5",
            "DR-PXG33-8",
            "DR-PXG33-9",
            "DR-PXG34-10.5",
            "DR-PXG34-11.5",
            "FR-PXG18-11",
            "FR-PXG18-3",
            "FR-PXG18-4",
            "FR-PXG18-5",
            "FR-PXG18-7",
            "FR-PXG18-9",
            "FR-PXG19-3",
            "FR-PXG19-5",
            "HR-PXG17-17",
            "HR-PXG17-19",
            "HR-PXG17-22",
            "HR-PXG17-25",
            "HR-PXG17-28",
            "HR-PXG17-31",
            "HR-PXG17-34",
            "HC-1314-LTNDR",
            "HC-1357-LTNFW",
            "HC-1358-LTNHY",
            "HC-LTNHCP11",
            "HC-LTNHCP17",
            "HC-LTNHCP19",
            "HC-LTNHCP22",
            "HC-LTNHCP25",
            "HC-LTNHCP28",
            "HC-LTNHCP3",
            "HC-LTNHCP31",
            "HC-LTNHCP34",
            "HC-LTNHCP4",
            "HC-LTNHCP5",
            "HC-LTNHCP7",
            "HC-LTNHCP9",
            "HC-LTNHCPX",
            "S-PX-DENALI-SIL-105I-6.0",
            "S-PX-DENALI-SIL-50I-4.0",
            "S-PX-DENALI-SIL-60I-5.0",
            "S-PX-DENALI-SIL-70I-5.5",
            "S-PX-DENALI-SIL-80I-6.0",
            "S-PX-DNLIFRST-BLU-50-5.0",
            "S-PX-DNLIFRST-BLU-50-5.5",
            "S-PX-DNLIFRST-BLU-50-6.0",
            "S-PX-DNLIFRST-BLU-60-5.5",
            "S-PX-DNLIFRST-BLU-60-6.0",
            "S-PX-DNLIFRST-BLU-60-6.5",
            "S-PX-DNLIFRST-BLU-70-6.5",
            "S-PX-HZRDG5-HYB-BLK-90-6.0",
            "S-PX-HZRDG5-HYB-BLK-90-6.5",
            "S-USTM-LINQ-BLUCB-55-A",
            "S-USTM-LINQ-BLUCB-55-R",
            "S-USTM-LINQ-BLUCB-65-R",
            "S-USTM-LINQ-WHT-65-S",
            "S-USTM-LINQ-WHT-65-X",
            "S-USTM-LINQ-WHT-75-S",
            "S-USTM-LINQ-WHT-75-X",
            "DL-PXG32-10.5",
            "DL-PXG32-9",
            "DL-PXG34-10.5",
            "FL-PXG18-11",
            "FL-PXG18-3",
            "FL-PXG18-4",
            "FL-PXG18-5",
            "FL-PXG18-7",
            "FL-PXG18-9",
            "FL-PXG19-3",
            "FL-PXG19-5",
            "FR-PXG15-11",
            "H-25PXG000296-OSFM-MS",
            "HC-GEN6-PATCH-11",
            "HL-PXG17-19",
            "HL-PXG17-22",
            "HL-PXG17-25",
            "HL-PXG17-28",
            "HL-PXG17-31",
            "HL-PXG17-34",
            "IL-PXG43-BLK-4",
            "IL-PXG43-BLK-5",
            "IL-PXG43-BLK-6",
            "IL-PXG43-BLK-7",
            "IL-PXG43-BLK-8",
            "IL-PXG43-BLK-9",
            "IL-PXG43-BLK-GW",
            "IL-PXG43-BLK-LW",
            "IL-PXG43-BLK-PW",
            "IL-PXG43-BLK-SW",
            "IL-PXG43-CHR-4",
            "IL-PXG43-CHR-5",
            "IL-PXG43-CHR-6",
            "IL-PXG43-CHR-7",
            "IL-PXG43-CHR-8",
            "IL-PXG43-CHR-9",
            "IL-PXG43-CHR-GW",
            "IL-PXG43-CHR-LW",
            "IL-PXG43-CHR-PW",
            "IL-PXG43-CHR-SW",
            "IL-PXG44-BLK-4",
            "IL-PXG44-BLK-5",
            "IL-PXG44-BLK-6",
            "IL-PXG44-BLK-7",
            "IL-PXG44-BLK-8",
            "IL-PXG44-BLK-9",
            "IL-PXG44-BLK-GW",
            "IL-PXG44-BLK-PW",
            "IL-PXG44-CHR-4",
            "IL-PXG44-CHR-5",
            "IL-PXG44-CHR-6",
            "IL-PXG44-CHR-7",
            "IL-PXG44-CHR-8",
            "IL-PXG44-CHR-9",
            "IL-PXG44-CHR-GW",
            "IL-PXG44-CHR-PW",
            "IL-PXG45-BLK-4",
            "IL-PXG45-BLK-5",
            "IL-PXG45-BLK-6",
            "IL-PXG45-BLK-7",
            "IL-PXG45-BLK-8",
            "IL-PXG45-BLK-9",
            "IL-PXG45-BLK-GW",
            "IL-PXG45-BLK-PW",
            "IL-PXG45-CHR-4",
            "IL-PXG45-CHR-5",
            "IL-PXG45-CHR-6",
            "IL-PXG45-CHR-7",
            "IL-PXG45-CHR-8",
            "IL-PXG45-CHR-9",
            "IL-PXG45-CHR-GW",
            "IL-PXG45-CHR-PW",
            "IL-PXG46-BLK-X",
            "IL-PXG46-CHR-X",
            "IR-PXG43-BLK-4",
            "IR-PXG43-BLK-5",
            "IR-PXG43-BLK-6",
            "IR-PXG43-BLK-7",
            "IR-PXG43-BLK-8",
            "IR-PXG43-BLK-9",
            "IR-PXG43-BLK-GW",
            "IR-PXG43-BLK-LW",
            "IR-PXG43-BLK-PW",
            "IR-PXG43-BLK-SW",
            "IR-PXG43-CHR-4",
            "IR-PXG43-CHR-5",
            "IR-PXG43-CHR-6",
            "IR-PXG43-CHR-7",
            "IR-PXG43-CHR-8",
            "IR-PXG43-CHR-9",
            "IR-PXG43-CHR-GW",
            "IR-PXG43-CHR-LW",
            "IR-PXG43-CHR-PW",
            "IR-PXG43-CHR-SW",
            "IR-PXG44-BLK-4",
            "IR-PXG44-BLK-5",
            "IR-PXG44-BLK-6",
            "IR-PXG44-BLK-7",
            "IR-PXG44-BLK-8",
            "IR-PXG44-BLK-9",
            "IR-PXG44-BLK-GW",
            "IR-PXG44-BLK-PW",
            "IR-PXG44-CHR-4",
            "IR-PXG44-CHR-5",
            "IR-PXG44-CHR-6",
            "IR-PXG44-CHR-7",
            "IR-PXG44-CHR-8",
            "IR-PXG44-CHR-9",
            "IR-PXG44-CHR-GW",
            "IR-PXG44-CHR-PW",
            "IR-PXG45-BLK-3",
            "IR-PXG45-BLK-4",
            "IR-PXG45-BLK-5",
            "IR-PXG45-BLK-6",
            "IR-PXG45-BLK-7",
            "IR-PXG45-BLK-8",
            "IR-PXG45-BLK-9",
            "IR-PXG45-BLK-GW",
            "IR-PXG45-BLK-PW",
            "IR-PXG45-CHR-3",
            "IR-PXG45-CHR-4",
            "IR-PXG45-CHR-5",
            "IR-PXG45-CHR-6",
            "IR-PXG45-CHR-7",
            "IR-PXG45-CHR-8",
            "IR-PXG45-CHR-9",
            "IR-PXG45-CHR-GW",
            "IR-PXG45-CHR-PW",
            "IR-PXG46-BLK-X",
            "IR-PXG46-CHR-X",
            "S-FUJI-SAKURA-40-L",
            "S-KBS-PGW-50-R",
            "S-KBS-PGW-60-R",
            "S-KBS-PGW-60-S",
            "S-KBS-PGW-60-X",
            "S-KBS-PGW-70-S",
            "S-KBS-PGW-70-X",
            "S-MC-KAILI-BLU-60-R",
            "S-MC-KAILI-BLU-60-S",
            "S-MC-KAILI-BLU-60-X",
            "S-MC-KAILI-BLU-70-S",
            "S-MC-KAILI-BLU-70-X",
            "S-TOURAD-FI-4-A",
            "S-TOURAD-FI-5-R",
            "S-TOURAD-FI-6-S",
            "S-TOURAD-FI-6-X",
            "S-TOURAD-FI-7-S",
            "S-TOURAD-FI-7-X",
            "S-TOURAD-GC-4-A",
            "S-TOURAD-GC-5-R",
            "S-TOURAD-GC-5-S",
            "S-TOURAD-GC-6-S",
            "B-PG-172-26CO-OG-MS",
            "G-TT-ICON-PXG-MID-BLK",
            "A-SHAFT-ADAPTER-DRIV",
            "A-SHAFT-ADAPTER-HYB",
            "A-SHAFT-ADPTR-DRIVLH",
            "A-SHAFT-ADPTR-HYBLH",
            "A-SHAFT-CTR-PC",
            "A-SSWEIGHT-25G",
            "A-SSWEIGHT-50G",
            "A-WEIGHTKIT-6PC",
            "A-WEIGHTKIT-DRIVER",
            "T-DISCWEIGHT-10G",
            "T-DISCWEIGHT-12.5G",
            "T-DISCWEIGHT-15G",
            "T-DISCWEIGHT-17.5G",
            "T-DISCWEIGHT-2.5G",
            "T-DISCWEIGHT-2.5G-TI",
            "T-DISCWEIGHT-20G",
            "T-DISCWEIGHT-5G",
            "T-DISCWEIGHT-7.5G",
            "T-G4IRONWGHT-10.5G",
            "T-G4IRONWGHT-10G",
            "T-G4IRONWGHT-11.5G",
            "T-G4IRONWGHT-11G",
            "T-G4IRONWGHT-12.5G",
            "T-G4IRONWGHT-12G",
            "T-G4IRONWGHT-13.5G",
            "T-G4IRONWGHT-13G",
            "T-G4IRONWGHT-14.5G",
            "T-G4IRONWGHT-14G",
            "T-G4IRONWGHT-15.5G",
            "T-G4IRONWGHT-15G",
            "T-G4IRONWGHT-16.5G",
            "T-G4IRONWGHT-16G",
            "T-G4IRONWGHT-17.5G",
            "T-G4IRONWGHT-17G",
            "T-G4IRONWGHT-18G",
            "T-G4IRONWGHT-2.5G",
            "T-G4IRONWGHT-3.5G",
            "T-G4IRONWGHT-3G",
            "T-G4IRONWGHT-4.5G",
            "T-G4IRONWGHT-4G",
            "T-G4IRONWGHT-5.5G",
            "T-G4IRONWGHT-5G",
            "T-G4IRONWGHT-6.5G",
            "T-G4IRONWGHT-6G",
            "T-G4IRONWGHT-7.5G",
            "T-G4IRONWGHT-7G",
            "T-G4IRONWGHT-8.5G",
            "T-G4IRONWGHT-8G",
            "T-G4IRONWGHT-9.5G",
            "T-G4IRONWGHT-9G",
            "T-G4IRONWGHT-SIL-10.5G",
            "T-G4IRONWGHT-SIL-10G",
            "T-G4IRONWGHT-SIL-11.5G",
            "T-G4IRONWGHT-SIL-11G",
            "T-G4IRONWGHT-SIL-12.5G",
            "T-G4IRONWGHT-SIL-12G",
            "T-G4IRONWGHT-SIL-13.5G",
            "T-G4IRONWGHT-SIL-13G",
            "T-G4IRONWGHT-SIL-14.5G",
            "T-G4IRONWGHT-SIL-14G",
            "T-G4IRONWGHT-SIL-15.5G",
            "T-G4IRONWGHT-SIL-15G",
            "T-G4IRONWGHT-SIL-16.5G",
            "T-G4IRONWGHT-SIL-16G",
            "T-G4IRONWGHT-SIL-17.5G",
            "T-G4IRONWGHT-SIL-17G",
            "T-G4IRONWGHT-SIL-18G",
            "T-G4IRONWGHT-SIL-3.5G",
            "T-G4IRONWGHT-SIL-3G",
            "T-G4IRONWGHT-SIL-4.5G",
            "T-G4IRONWGHT-SIL-4G",
            "T-G4IRONWGHT-SIL-5.5G",
            "T-G4IRONWGHT-SIL-5G",
            "T-G4IRONWGHT-SIL-6.5G",
            "T-G4IRONWGHT-SIL-6G",
            "T-G4IRONWGHT-SIL-7.5G",
            "T-G4IRONWGHT-SIL-7G",
            "T-G4IRONWGHT-SIL-8.5G",
            "T-G4IRONWGHT-SIL-8G",
            "T-G4IRONWGHT-SIL-9.5G",
            "T-G4IRONWGHT-SIL-9G",
            "TIP WEIGHT- .5 GRAM",
            "TIP WEIGHT- 1.5 GRAM",
            "TIP WEIGHT- 3.5 GRAM",
            "T-TIPWEIGHT-.5G",
            "T-TIPWEIGHT-1.5G",
            "T-TIPWEIGHT-1G",
            "T-TIPWEIGHT-2.5G",
            "T-TIPWEIGHT-2G",
            "T-TIPWEIGHT-3.5G",
            "T-TIPWEIGHT-3G",
            "T-TIPWEIGHT-4G",
            "T-TIPWEIGHT-5G",
            "T-TIPWEIGHT-6G",
            "T-TIPWEIGHT-7G",
            "T-TIPWEIGHT-8G",
            "IRON FERRULE .360 TIP",
            "T-FERRULE-IRON-360",
            "T-FERRULE-WEDGE-360",
            "T-IRON-FERRULE-.355",
            "T-IRON-FERRULE-.360",
            "T-PUTTER FERRULE 1",
            "T-WEDGE-FERRULE-.355",
            "T-WEDGE-FERRULE-.360",
            "T-FERRULE-WEDGE-355",
            "T-FERRULE-IRON-355",
            "T-GEN8IRWGT-BLK-10G",
            "T-GEN8IRWGT-BLK-11G",
            "T-GEN8IRWGT-BLK-12G",
            "T-GEN8IRWGT-BLK-2G",
            "T-GEN8IRWGT-BLK-3G",
            "T-GEN8IRWGT-BLK-4G",
            "T-GEN8IRWGT-BLK-5G",
            "T-GEN8IRWGT-BLK-6G",
            "T-GEN8IRWGT-BLK-7G",
            "T-GEN8IRWGT-BLK-8G",
            "T-GEN8IRWGT-BLK-9G",
            "T-GEN8IRWGT-SIL-10G",
            "T-GEN8IRWGT-SIL-11G",
            "T-GEN8IRWGT-SIL-12G",
            "T-GEN8IRWGT-SIL-2G",
            "T-GEN8IRWGT-SIL-3G",
            "T-GEN8IRWGT-SIL-4G",
            "T-GEN8IRWGT-SIL-5G",
            "T-GEN8IRWGT-SIL-6G",
            "T-GEN8IRWGT-SIL-7G",
            "T-GEN8IRWGT-SIL-8G",
            "T-GEN8IRWGT-SIL-9G",
            "T-FERRULE-PUTTER",
            "B-PG-172-NVYWHT-MS",
            "B-PG-173-NVYWHT-MS",
            "B-PG-244-NVYWHT-MS",
            "G-PXG-PG-SLTPST-MID-L-BLK",
            "G-PXG-PG-SLTPST-MID-R-BLK",
            "HC-1381-RLMALCS",
            "PL-PXG7-HOTROD-BLK-SL1",
            "PL-PXG7-HOTROD-BLK-SL2",
            "PR-PXG7-HOTROD-BLK-SL1",
            "PR-PXG7-HOTROD-BLK-SL2",
            "S-PX-DNLIFRST-BLU-HYB-70-5.5",
            "S-PX-DNLIFRST-BLU-HYB-70-6.0",
            "A-Q26442-ASM-2-MS",
            "B-PG-172-DRKBLK-MS",
            "B-PG-172-NVYWHT-MS",
            "B-PG-173-26CO-OG-MS",
            "B-PG-173-DRKBLK-MS",
            "B-PG-173-NVYWHT-MS",
            "B-PG-244-NVYWHT-MS",
            "B-PG-245-DRKBLK-MS",
            "G-PXG-PG-SLTPST-STD-L-BLK",
            "G-PXG-PG-SLTPST-STD-R-BLK",
            "G-TT-ICON-PXG-OVR-BLK",
            "PL-PXG7-HOTROD-BLK-SL4",
            "WL-PXG8-BLK-50-10S",
            "WL-PXG8-BLK-52-10S",
            "WL-PXG8-BLK-54-10S",
            "WL-PXG8-BLK-54-13BP",
            "WL-PXG8-BLK-56-10S",
            "WL-PXG8-BLK-56-13BP",
            "WL-PXG8-BLK-58-10S",
            "WL-PXG8-BLK-58-13BP",
            "WL-PXG8-BLK-60-10S",
            "WL-PXG8-BLK-60-13BP",
            "WL-PXG8-CHR-50-10S",
            "WL-PXG8-CHR-52-10S",
            "WL-PXG8-CHR-54-10S",
            "WL-PXG8-CHR-54-13BP",
            "WL-PXG8-CHR-56-10S",
            "WL-PXG8-CHR-56-13BP",
            "WL-PXG8-CHR-58-10S",
            "WL-PXG8-CHR-58-13BP",
            "WL-PXG8-CHR-60-10S",
            "WL-PXG8-CHR-60-13BP",
            "WR-PXG8-BLK-52-10S",
            "WR-PXG8-BLK-54-13BP",
            "WR-PXG8-BLK-56-10S",
            "WR-PXG8-BLK-56-13BP",
            "WR-PXG8-BLK-58-10S",
            "WR-PXG8-BLK-58-13BP",
            "WR-PXG8-BLK-60-10S",
            "WR-PXG8-BLK-60-13BP",
            "WR-PXG8-CHR-50-10S",
            "WR-PXG8-CHR-52-10S",
            "WR-PXG8-CHR-54-10S",
            "WR-PXG8-CHR-56-10S",
            "WR-PXG8-CHR-56-13BP",
            "WR-PXG8-CHR-58-10S",
            "WR-PXG8-CHR-58-13BP",
            "WR-PXG8-CHR-60-10S",
            "WR-PXG8-CHR-60-13BP",
            "S-PX-DNLIFRST-BLU-HYB-80-6.5",
            "WR-PXG8-BLK-50-10S",
            "B-PG-172-XSHLD-WHT-MS",
            "G-TT-ICON-PXG-UND-BLK",
            "WR-PXG8-BLK-54-10S",
            "WR-PXG8-CHR-54-13BP",
            "S-PX-DNLIFRST-RED-50-5.0",
            "S-PX-DNLIFRST-RED-50-5.5",
            "S-PX-DNLIFRST-RED-50-6.0",
            "S-PX-DNLIFRST-RED-60-5.5",
            "S-PX-DNLIFRST-RED-60-6.0",
            "S-TOURAD-DI-5S-ORG",
            "S-TOURAD-DI-6S-ORG",
            "S-TOURAD-DI-7S-ORG",
            "IR-PXG43-IHOS-CHR-7",
            "IR-PXG44-IHOS-CHR-7",
            "IR-PXG45-IHOS-CHR-7",
            "S-PX-DNLIFRST-RED-40-4.0",
            "S-NIP-MODPRO-105X-7",
            "B-PG-286-MS",
            "PR-PXG7-ALLAN-TU-480-BLK",
            "FR-PXG18-9-C",
            "FR-PXG18-4-C",
            "FL-PXG18-3-C",
            "FR-PXG18-3-C",
            "B-PG-172-XGB-MS",
            "B-PG-173-14-XGB-MS",
            "B-PG-173-XGB-MS",
            "B-PG-244-XGB-MS",
            "A-Q25645-ASM-2-MS",
            "H-25PXG000379-OSFM-MS",
            "H-25PXG000382-OSFM-MS",
            "H-25PXG000383-OSFM-MS",
            "H-25PXG000384-OSFM-MS",
            "HC-1415-26SSMAL",
            "HC-1416-26SSBLD",
            "B-PG-172PU-26SS-MS",
            "B-PG-173PU-26SS-MS",
            "GB-DOZ-XTTR-WHT-AF-MS",
            "GB-DOZ-XTTR-WHT-ARMY-MS",
            "GB-DOZ-XTTR-WHT-NAVY-MS",
            "GB-DOZ-XTTR-WHT-USMC-MS",
            "GB-DOZ-XTTRX-WHT-AF-MS",
            "GB-DOZ-XTTRX-WHT-USMC-MS",
            "TT-700",
            "IL-PXG44-IHOS-CHR-7"
        ]

        # Procesar cada grupo de columnas
        grupo1 = procesar_grupo(dfrecibo, 'Inventory ID', 'Description', 'Quantity')
        grupo2 = procesar_grupo(dfrecibo, 'Inventory ID.1', 'Description.1', 'Quantity.1')
        grupo3 = procesar_grupo(dfrecibo, 'Inventory ID.2', 'Description.2', 'Quantity.2')

        # Renombrar columnas para la comparación
        grupo1.columns = ['Inventory_ID', 'Acumatica']
        grupo2.columns = ['Inventory_ID', 'Shipment']
        grupo3.columns = ['Inventory_ID', 'IES']

        # Combinar todos los grupos
        comparacion = grupo1.merge(grupo2, on='Inventory_ID', how='outer')
        comparacion = comparacion.merge(grupo3, on='Inventory_ID', how='outer')

        # Rellenar NaN con 0 para los cálculos
        comparacion[['Acumatica', 'Shipment', 'IES']] = comparacion[['Acumatica', 'Shipment', 'IES']].fillna(0)

        # Calcular diferencias
        comparacion['Acumatica vs Shipment'] = comparacion['Acumatica'] - comparacion['Shipment']
        comparacion['Acumatica vs IES'] = comparacion['Acumatica'] - comparacion['IES']
        comparacion['Shipment vs IES'] = comparacion['Shipment'] - comparacion['IES']

        # Marcar si hay diferencias
        comparacion['Resultados'] = comparacion.apply(
            lambda row: 'Revisar' if (row['Acumatica vs Shipment'] != 0) or 
                                    (row['Acumatica vs IES'] != 0) or 
                                    (row['Shipment vs IES'] != 0) 
                        else 'Correcto',
            axis=1
        )
        comparacion['Nuevo Np'] = comparacion['Inventory_ID'].apply(
            lambda x: 'Nuevo' if str(x) not in nps else ''
        )

        #Details
        details1 = dfrecibo_details[['Inventory ID', 'Description', 'Quantity']].copy()
        details2 = dfrecibo_details[['Inventory ID.1','Quantity.1']].copy()
        details3 = dfrecibo_details[['Inventory ID.2', 'Quantity.2']].copy()

        details1.columns = ['Inventory ID', 'Description', 'Acumatica']
        details2.columns = ['Inventory ID', 'Shipment']
        details3.columns = ['Inventory ID', 'IES']

        details1.sort_values('Acumatica', inplace=True)
        details2.sort_values('Shipment', inplace=True)
        details3.sort_values('IES', inplace=True)


        details1['linea'] = details1.groupby('Inventory ID').cumcount()
        details2['linea'] = details2.groupby('Inventory ID').cumcount()
        details3['linea'] = details3.groupby('Inventory ID').cumcount()

        details = details1.merge(
            details2,
            on=['Inventory ID', 'linea'],
            how='outer'
        )

        details = details.merge(
            details3,
            on=['Inventory ID', 'linea'],
            how='outer'
        )

        details.drop(columns='linea', inplace=True)

        details[['Acumatica', 'Shipment', 'IES']] = details[['Acumatica', 'Shipment', 'IES']].fillna(0)
        # Marcar si hay diferencias
        details['Resultados'] = details.apply(
            lambda row: 'Revisar' if (row['Acumatica'] != row['Shipment']) or 
                                    (row['Acumatica'] != row['IES']) or 
                                    (row['Shipment'] != row['IES']) 
                        else 'Correcto',
            axis=1
        )

        bags = r'^(B-1|B-6|B-C|B-I|B-P|B-U|B-W)'
        balls = r'^(G4-)'
        ferrule = r'^(IRO|T-F|T-I|T-P|T-W)'
        grips = r'^(G-G|G-L|G-P|G-S|G-W|G-T)'
        accee = r'^(A-S|A-W|A-T|A-U|A-Q)'
        caps = r'^(H-2|H-6|H-U)'
        weights = r'^(T-D|T-G|TIP|T-T)'
        headcovers = r'^(HC-|H-2)'
        heads = r'^(DL-|DR-|FL-|FR-|HL-|HR-|IL-|IR-|PL-|PL4|PR-|PR4|PR5|WL-|WR-)'
        hosel = r'^(PL3|PR3|PU3)'
        shaft = r'^(S-A|S-D|S-E|S-F|S-G|S-K|S-M|S-N|S-P|S-T|S-U)'

        details['Tipo'] = details['Inventory ID'].apply(
            lambda x: 'BAG' if re.match(bags, str(x)) else
                      'GOLF BALLS' if re.match(balls, str(x)) else
                      'FERRULES' if re.match(ferrule, str(x)) else
                      'GRIPS' if re.match(grips, str(x)) else
                      'ACCESSORIES' if re.match(accee, str(x)) else
                      'CAPS' if re.match(caps, str(x)) else
                      'WEIGHTS' if re.match(weights, str(x)) else
                      'HEADCOVERS' if re.match(headcovers, str(x)) else
                      'HEADS' if re.match(heads, str(x)) else
                      'HOSEL' if re.match(hosel, str(x)) else
                      'SHAFT' if re.match(shaft, str(x)) else ''
        )

        
        cantidades_esperadas = {
            'BAG': [20,25,24],
            'SHAFT': [50, 100],
            'HEADS': [20,25],
            'GOLF BALLS': [24],
            'GRIPS': [100, 120, 150],
        }

        # Función para verificar si la cantidad es esperada
        def verificar_cantidad(row):
            tipo = row['Tipo']
            cantidad = row['Shipment'] 
            
            # Si el tipo no está en el diccionario, retornar 'Desconocido'
            if tipo not in cantidades_esperadas:
                return 'Desconocido'
            
            # Verificar si la cantidad está en las cantidades esperadas
            if cantidad in cantidades_esperadas[tipo]:
                return 'Completa'
            else:
                return 'Parcial'

        # Aplicar la función para crear la nueva columna
        details['Importacion'] = details.apply(verificar_cantidad, axis=1)

        details = details[['Tipo', 'Inventory ID', 'Description', 'Acumatica', 'Shipment', 'IES', 'Resultados', 'Importacion']]


        # Create an Excel file with multiple sheet
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            comparacion.to_excel(writer, sheet_name='Resumen', index=False) 
            
            workbook = writer.book
            worksheet = writer.sheets['Resumen']
            

            
            # Definir colores
            COLORES = {
                'Correcto': PatternFill(start_color='FFC6EFCE', end_color='FFC6EFCE', fill_type='solid'),
                'Revisar': PatternFill(start_color='FFFFC7CE', end_color='FFFFC7CE', fill_type='solid'),
                'Completa': PatternFill(start_color='FFC6EFCE', end_color='FFC6EFCE', fill_type='solid'),
                'Parcial': PatternFill(start_color='FFFFEB9C', end_color='FFFFEB9C', fill_type='solid')

            }

            HEADER_FONT = Font(bold=True, size=11)

            BORDER = Border(
                    left=Side(style='thin', color='D0D0D0'),
                    right=Side(style='thin', color='D0D0D0'),
                    top=Side(style='thin', color='D0D0D0'),
                    bottom=Side(style='thin', color='D0D0D0')
                )

            for col in range(1, len(comparacion.columns) + 1):
                cell = worksheet.cell(row=1, column=col)
                cell.font = HEADER_FONT
                cell.alignment = Alignment(horizontal='center', vertical='center')
                cell.border = BORDER
            
            # Encontrar columna 'Comments'
            status_col_idx = None
            for idx, col in enumerate(comparacion.columns, 1):
                if col == 'Resultados':
                    status_col_idx = idx
                    break
            
            # Aplicar colores a la columna Comments
            if status_col_idx:
                for row in range(2, len(comparacion) + 2):
                    cell = worksheet.cell(row=row, column=status_col_idx)
                    status_value = cell.value
                    
                    if status_value in COLORES:
                        cell.fill = COLORES[status_value]
                
                # Centrar y poner en negrita
                for row in range(1, len(comparacion) + 2):
                    cell = worksheet.cell(row=row, column=status_col_idx)
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                    if row > 1:  # Solo negrita para datos, no encabezados
                        cell.font = Font(bold=True)
            
            # Autoajustar columnas
            for column in worksheet.columns:
                max_length = 0
                column_letter = get_column_letter(column[0].column)
                
                for cell in column:
                    try:
                        cell_length = len(str(cell.value))
                        if cell_length > max_length:
                            max_length = cell_length
                    except:
                        pass
                
                adjusted_width = min(max_length + 2, 50)
                worksheet.column_dimensions[column_letter].width = adjusted_width

            #---------Segunda Hoja-----------------------------------------------------------------------
            details.to_excel(writer, sheet_name='Detalles', index=False)
            worksheet2 = writer.sheets['Detalles']
            for col in range(1, len(details.columns) + 1):
                cell = worksheet2.cell(row=1, column=col)
                cell.font = HEADER_FONT
                cell.alignment = Alignment(horizontal='center', vertical='center')
                cell.border = BORDER
            
            # Encontrar columna 'Comments'
            status_col_idx = None
            for idx, col in enumerate(details.columns, 1):
                if col == 'Resultados':
                    status_col_idx = idx
                    break
            
            # Aplicar colores a la columna Comments
            if status_col_idx:
                for row in range(2, len(details) + 2):
                    cell = worksheet2.cell(row=row, column=status_col_idx)
                    status_value = cell.value
                    
                    if status_value in COLORES:
                        cell.fill = COLORES[status_value]
                
                # Centrar y poner en negrita
                for row in range(1, len(details) + 2):
                    cell = worksheet2.cell(row=row, column=status_col_idx)
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                    if row > 1:  # Solo negrita para datos, no encabezados
                        cell.font = Font(bold=True)

            # Encontrar columna 'Importacion'
            status_col_idx = None
            for idx, col in enumerate(details.columns, 1):
                if col == 'Importacion':
                    status_col_idx = idx
                    break
            
            # Aplicar colores a la columna Comments
            if status_col_idx:
                for row in range(2, len(details) + 2):
                    cell = worksheet2.cell(row=row, column=status_col_idx)
                    status_value = cell.value
                    
                    if status_value in COLORES:
                        cell.fill = COLORES[status_value]
                
                # Centrar y poner en negrita
                for row in range(1, len(details) + 2):
                    cell = worksheet2.cell(row=row, column=status_col_idx)
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                    if row > 1:  # Solo negrita para datos, no encabezados
                        cell.font = Font(bold=True)
            
            # Autoajustar columnas
            for column in worksheet2.columns:
                max_length = 0
                column_letter = get_column_letter(column[0].column)
                
                for cell in column:
                    try:
                        cell_length = len(str(cell.value))
                        if cell_length > max_length:
                            max_length = cell_length
                    except:
                        pass
                
                adjusted_width = min(max_length + 2, 50)
                worksheet2.column_dimensions[column_letter].width = adjusted_width
        output.seek(0)
        return StreamingResponse(
            output,
            media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            headers={
                'Content-Disposition': 'attachment; filename="Analisis_Importaciones.xlsx"'
            }
        )


    except UnicodeDecodeError:
        raise HTTPException(status_code=400, detail="Error de codificación.")
    except pd.errors.ParserError:
        raise HTTPException(status_code=400, detail="Error al analizar el US Chase.")
    except Exception as e:
        print("ERROR VALIDATION RECEIPT:", e)
        raise HTTPException(status_code=500, detail=str(e))